//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.237
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace SlvHanbaiClient.svcPaymentCreditBalance {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPaymentCreditBalance", Namespace="http://schemas.datacontract.org/2004/07/SlvHanbai.Web.Class.Entity")]
    public partial class EntityPaymentCreditBalance : SlvHanbaiClient.svcPaymentCreditBalance.EntityBase {
        
        private double _before_payment_credit_balacneField;
        
        private double _before_payment_credit_balacne_updField;
        
        private bool _exec_flgField;
        
        private int _lock_flgField;
        
        private string _memoField;
        
        private string _purchase_idField;
        
        private string _purchase_nmField;
        
        private long _rec_noField;
        
        private double _this_payment_cash_percentField;
        
        private double _this_payment_cash_priceField;
        
        private double _this_payment_credit_balanceField;
        
        private double _this_purchase_priceField;
        
        private double _this_taxField;
        
        private string _ymField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _before_payment_credit_balacne {
            get {
                return this._before_payment_credit_balacneField;
            }
            set {
                if ((this._before_payment_credit_balacneField.Equals(value) != true)) {
                    this._before_payment_credit_balacneField = value;
                    this.RaisePropertyChanged("_before_payment_credit_balacne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _before_payment_credit_balacne_upd {
            get {
                return this._before_payment_credit_balacne_updField;
            }
            set {
                if ((this._before_payment_credit_balacne_updField.Equals(value) != true)) {
                    this._before_payment_credit_balacne_updField = value;
                    this.RaisePropertyChanged("_before_payment_credit_balacne_upd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _exec_flg {
            get {
                return this._exec_flgField;
            }
            set {
                if ((this._exec_flgField.Equals(value) != true)) {
                    this._exec_flgField = value;
                    this.RaisePropertyChanged("_exec_flg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _lock_flg {
            get {
                return this._lock_flgField;
            }
            set {
                if ((this._lock_flgField.Equals(value) != true)) {
                    this._lock_flgField = value;
                    this.RaisePropertyChanged("_lock_flg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _memo {
            get {
                return this._memoField;
            }
            set {
                if ((object.ReferenceEquals(this._memoField, value) != true)) {
                    this._memoField = value;
                    this.RaisePropertyChanged("_memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _purchase_id {
            get {
                return this._purchase_idField;
            }
            set {
                if ((object.ReferenceEquals(this._purchase_idField, value) != true)) {
                    this._purchase_idField = value;
                    this.RaisePropertyChanged("_purchase_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _purchase_nm {
            get {
                return this._purchase_nmField;
            }
            set {
                if ((object.ReferenceEquals(this._purchase_nmField, value) != true)) {
                    this._purchase_nmField = value;
                    this.RaisePropertyChanged("_purchase_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _rec_no {
            get {
                return this._rec_noField;
            }
            set {
                if ((this._rec_noField.Equals(value) != true)) {
                    this._rec_noField = value;
                    this.RaisePropertyChanged("_rec_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _this_payment_cash_percent {
            get {
                return this._this_payment_cash_percentField;
            }
            set {
                if ((this._this_payment_cash_percentField.Equals(value) != true)) {
                    this._this_payment_cash_percentField = value;
                    this.RaisePropertyChanged("_this_payment_cash_percent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _this_payment_cash_price {
            get {
                return this._this_payment_cash_priceField;
            }
            set {
                if ((this._this_payment_cash_priceField.Equals(value) != true)) {
                    this._this_payment_cash_priceField = value;
                    this.RaisePropertyChanged("_this_payment_cash_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _this_payment_credit_balance {
            get {
                return this._this_payment_credit_balanceField;
            }
            set {
                if ((this._this_payment_credit_balanceField.Equals(value) != true)) {
                    this._this_payment_credit_balanceField = value;
                    this.RaisePropertyChanged("_this_payment_credit_balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _this_purchase_price {
            get {
                return this._this_purchase_priceField;
            }
            set {
                if ((this._this_purchase_priceField.Equals(value) != true)) {
                    this._this_purchase_priceField = value;
                    this.RaisePropertyChanged("_this_purchase_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _this_tax {
            get {
                return this._this_taxField;
            }
            set {
                if ((this._this_taxField.Equals(value) != true)) {
                    this._this_taxField = value;
                    this.RaisePropertyChanged("_this_tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ym {
            get {
                return this._ymField;
            }
            set {
                if ((object.ReferenceEquals(this._ymField, value) != true)) {
                    this._ymField = value;
                    this.RaisePropertyChanged("_ym");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/SlvHanbai.Web.Class.Entity")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance))]
    public partial class EntityBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="svcPaymentCreditBalance.svcPaymentCreditBalance")]
    public interface svcPaymentCreditBalance {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:svcPaymentCreditBalance/GetPaymentCreditBalanceList", ReplyAction="urn:svcPaymentCreditBalance/GetPaymentCreditBalanceListResponse")]
        System.IAsyncResult BeginGetPaymentCreditBalanceList(string random, string strWhereSql, string strOrderBySql, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance> EndGetPaymentCreditBalanceList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:svcPaymentCreditBalance/UpdatePaymentCreditBalance", ReplyAction="urn:svcPaymentCreditBalance/UpdatePaymentCreditBalanceResponse")]
        System.IAsyncResult BeginUpdatePaymentCreditBalance(string random, int type, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance> entity, System.AsyncCallback callback, object asyncState);
        
        string EndUpdatePaymentCreditBalance(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface svcPaymentCreditBalanceChannel : SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPaymentCreditBalanceListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPaymentCreditBalanceListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdatePaymentCreditBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdatePaymentCreditBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class svcPaymentCreditBalanceClient : System.ServiceModel.ClientBase<SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance>, SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance {
        
        private BeginOperationDelegate onBeginGetPaymentCreditBalanceListDelegate;
        
        private EndOperationDelegate onEndGetPaymentCreditBalanceListDelegate;
        
        private System.Threading.SendOrPostCallback onGetPaymentCreditBalanceListCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdatePaymentCreditBalanceDelegate;
        
        private EndOperationDelegate onEndUpdatePaymentCreditBalanceDelegate;
        
        private System.Threading.SendOrPostCallback onUpdatePaymentCreditBalanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public svcPaymentCreditBalanceClient() {
        }
        
        public svcPaymentCreditBalanceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public svcPaymentCreditBalanceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcPaymentCreditBalanceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcPaymentCreditBalanceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("CookieContainer を設定できません。バインドに HttpCookieContainerBindingElement が含まれていることを確認してくだ" +
                            "さい。");
                }
            }
        }
        
        public event System.EventHandler<GetPaymentCreditBalanceListCompletedEventArgs> GetPaymentCreditBalanceListCompleted;
        
        public event System.EventHandler<UpdatePaymentCreditBalanceCompletedEventArgs> UpdatePaymentCreditBalanceCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance.BeginGetPaymentCreditBalanceList(string random, string strWhereSql, string strOrderBySql, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPaymentCreditBalanceList(random, strWhereSql, strOrderBySql, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance> SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance.EndGetPaymentCreditBalanceList(System.IAsyncResult result) {
            return base.Channel.EndGetPaymentCreditBalanceList(result);
        }
        
        private System.IAsyncResult OnBeginGetPaymentCreditBalanceList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string random = ((string)(inValues[0]));
            string strWhereSql = ((string)(inValues[1]));
            string strOrderBySql = ((string)(inValues[2]));
            return ((SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance)(this)).BeginGetPaymentCreditBalanceList(random, strWhereSql, strOrderBySql, callback, asyncState);
        }
        
        private object[] OnEndGetPaymentCreditBalanceList(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance> retVal = ((SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance)(this)).EndGetPaymentCreditBalanceList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPaymentCreditBalanceListCompleted(object state) {
            if ((this.GetPaymentCreditBalanceListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPaymentCreditBalanceListCompleted(this, new GetPaymentCreditBalanceListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPaymentCreditBalanceListAsync(string random, string strWhereSql, string strOrderBySql) {
            this.GetPaymentCreditBalanceListAsync(random, strWhereSql, strOrderBySql, null);
        }
        
        public void GetPaymentCreditBalanceListAsync(string random, string strWhereSql, string strOrderBySql, object userState) {
            if ((this.onBeginGetPaymentCreditBalanceListDelegate == null)) {
                this.onBeginGetPaymentCreditBalanceListDelegate = new BeginOperationDelegate(this.OnBeginGetPaymentCreditBalanceList);
            }
            if ((this.onEndGetPaymentCreditBalanceListDelegate == null)) {
                this.onEndGetPaymentCreditBalanceListDelegate = new EndOperationDelegate(this.OnEndGetPaymentCreditBalanceList);
            }
            if ((this.onGetPaymentCreditBalanceListCompletedDelegate == null)) {
                this.onGetPaymentCreditBalanceListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPaymentCreditBalanceListCompleted);
            }
            base.InvokeAsync(this.onBeginGetPaymentCreditBalanceListDelegate, new object[] {
                        random,
                        strWhereSql,
                        strOrderBySql}, this.onEndGetPaymentCreditBalanceListDelegate, this.onGetPaymentCreditBalanceListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance.BeginUpdatePaymentCreditBalance(string random, int type, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance> entity, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdatePaymentCreditBalance(random, type, entity, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance.EndUpdatePaymentCreditBalance(System.IAsyncResult result) {
            return base.Channel.EndUpdatePaymentCreditBalance(result);
        }
        
        private System.IAsyncResult OnBeginUpdatePaymentCreditBalance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string random = ((string)(inValues[0]));
            int type = ((int)(inValues[1]));
            System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance> entity = ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance>)(inValues[2]));
            return ((SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance)(this)).BeginUpdatePaymentCreditBalance(random, type, entity, callback, asyncState);
        }
        
        private object[] OnEndUpdatePaymentCreditBalance(System.IAsyncResult result) {
            string retVal = ((SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance)(this)).EndUpdatePaymentCreditBalance(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdatePaymentCreditBalanceCompleted(object state) {
            if ((this.UpdatePaymentCreditBalanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdatePaymentCreditBalanceCompleted(this, new UpdatePaymentCreditBalanceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdatePaymentCreditBalanceAsync(string random, int type, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance> entity) {
            this.UpdatePaymentCreditBalanceAsync(random, type, entity, null);
        }
        
        public void UpdatePaymentCreditBalanceAsync(string random, int type, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance> entity, object userState) {
            if ((this.onBeginUpdatePaymentCreditBalanceDelegate == null)) {
                this.onBeginUpdatePaymentCreditBalanceDelegate = new BeginOperationDelegate(this.OnBeginUpdatePaymentCreditBalance);
            }
            if ((this.onEndUpdatePaymentCreditBalanceDelegate == null)) {
                this.onEndUpdatePaymentCreditBalanceDelegate = new EndOperationDelegate(this.OnEndUpdatePaymentCreditBalance);
            }
            if ((this.onUpdatePaymentCreditBalanceCompletedDelegate == null)) {
                this.onUpdatePaymentCreditBalanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdatePaymentCreditBalanceCompleted);
            }
            base.InvokeAsync(this.onBeginUpdatePaymentCreditBalanceDelegate, new object[] {
                        random,
                        type,
                        entity}, this.onEndUpdatePaymentCreditBalanceDelegate, this.onUpdatePaymentCreditBalanceCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance CreateChannel() {
            return new svcPaymentCreditBalanceClientChannel(this);
        }
        
        private class svcPaymentCreditBalanceClientChannel : ChannelBase<SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance>, SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance {
            
            public svcPaymentCreditBalanceClientChannel(System.ServiceModel.ClientBase<SlvHanbaiClient.svcPaymentCreditBalance.svcPaymentCreditBalance> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetPaymentCreditBalanceList(string random, string strWhereSql, string strOrderBySql, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = random;
                _args[1] = strWhereSql;
                _args[2] = strOrderBySql;
                System.IAsyncResult _result = base.BeginInvoke("GetPaymentCreditBalanceList", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance> EndGetPaymentCreditBalanceList(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance> _result = ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance>)(base.EndInvoke("GetPaymentCreditBalanceList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdatePaymentCreditBalance(string random, int type, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCreditBalance.EntityPaymentCreditBalance> entity, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = random;
                _args[1] = type;
                _args[2] = entity;
                System.IAsyncResult _result = base.BeginInvoke("UpdatePaymentCreditBalance", _args, callback, asyncState);
                return _result;
            }
            
            public string EndUpdatePaymentCreditBalance(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("UpdatePaymentCreditBalance", _args, result)));
                return _result;
            }
        }
    }
}
