//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.237
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace SlvHanbai.Web.Reports.xsd {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("_SalesBalancePrint")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class _SalesBalancePrint : global::System.Data.DataSet {
        
        private SalesBalancePrintDataTable tableSalesBalancePrint;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public _SalesBalancePrint() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected _SalesBalancePrint(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["SalesBalancePrint"] != null)) {
                    base.Tables.Add(new SalesBalancePrintDataTable(ds.Tables["SalesBalancePrint"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SalesBalancePrintDataTable SalesBalancePrint {
            get {
                return this.tableSalesBalancePrint;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            _SalesBalancePrint cln = ((_SalesBalancePrint)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["SalesBalancePrint"] != null)) {
                    base.Tables.Add(new SalesBalancePrintDataTable(ds.Tables["SalesBalancePrint"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableSalesBalancePrint = ((SalesBalancePrintDataTable)(base.Tables["SalesBalancePrint"]));
            if ((initTable == true)) {
                if ((this.tableSalesBalancePrint != null)) {
                    this.tableSalesBalancePrint.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "SalesBalancePrint";
            this.Prefix = "";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableSalesBalancePrint = new SalesBalancePrintDataTable();
            base.Tables.Add(this.tableSalesBalancePrint);
            this.ExtendedProperties.Add("Generator_DataSetName", "_SalesBalancePrint");
            this.ExtendedProperties.Add("Generator_UserDSName", "SalesBalancePrint");
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeSalesBalancePrint() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            _SalesBalancePrint ds = new _SalesBalancePrint();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void SalesBalancePrintRowChangeEventHandler(object sender, SalesBalancePrintRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class SalesBalancePrintDataTable : global::System.Data.TypedTableBase<SalesBalancePrintRow> {
            
            private global::System.Data.DataColumn columnCOMPANY_ID;
            
            private global::System.Data.DataColumn columnGROUP_ID;
            
            private global::System.Data.DataColumn columnGROUP_SUM;
            
            private global::System.Data.DataColumn columnYM;
            
            private global::System.Data.DataColumn columnINVOICE_ID;
            
            private global::System.Data.DataColumn columnINVOICE_NAME;
            
            private global::System.Data.DataColumn columnSALES_CREDIT_INIT_PRICE;
            
            private global::System.Data.DataColumn columnSUM_NO_TAX_PRICE;
            
            private global::System.Data.DataColumn columnSUM_TAX;
            
            private global::System.Data.DataColumn columnSUM_PRICE;
            
            private global::System.Data.DataColumn columnBEFORE_SALES_CREDIT_BALANCE;
            
            private global::System.Data.DataColumn columnTHIS_RECEIPT_PRICE;
            
            private global::System.Data.DataColumn columnTHIS_RECEIPT_PERCENT;
            
            private global::System.Data.DataColumn columnTHIS_SALES_PRICE;
            
            private global::System.Data.DataColumn columnTHIS_SALES_TAX;
            
            private global::System.Data.DataColumn columnTHIS_SALES_CREDIT_BALANCE;
            
            private global::System.Data.DataColumn columnTHIS_CASH_PRICE;
            
            private global::System.Data.DataColumn columnTHIS_ACCOUNT_PRICE;
            
            private global::System.Data.DataColumn columnTHIS_COMMISSION_PRICE;
            
            private global::System.Data.DataColumn columnTHIS_BILL_PRICE;
            
            private global::System.Data.DataColumn columnTHIS_ANOTHER_PRICE;
            
            private global::System.Data.DataColumn columnUSER_NAME;
            
            private global::System.Data.DataColumn columnGROUP_RANGE;
            
            private global::System.Data.DataColumn columnSTRING_WHERE1;
            
            private global::System.Data.DataColumn columnSTRING_WHERE2;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public SalesBalancePrintDataTable() {
                this.TableName = "SalesBalancePrint";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal SalesBalancePrintDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected SalesBalancePrintDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn COMPANY_IDColumn {
                get {
                    return this.columnCOMPANY_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn GROUP_IDColumn {
                get {
                    return this.columnGROUP_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn GROUP_SUMColumn {
                get {
                    return this.columnGROUP_SUM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn YMColumn {
                get {
                    return this.columnYM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn INVOICE_IDColumn {
                get {
                    return this.columnINVOICE_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn INVOICE_NAMEColumn {
                get {
                    return this.columnINVOICE_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SALES_CREDIT_INIT_PRICEColumn {
                get {
                    return this.columnSALES_CREDIT_INIT_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SUM_NO_TAX_PRICEColumn {
                get {
                    return this.columnSUM_NO_TAX_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SUM_TAXColumn {
                get {
                    return this.columnSUM_TAX;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SUM_PRICEColumn {
                get {
                    return this.columnSUM_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BEFORE_SALES_CREDIT_BALANCEColumn {
                get {
                    return this.columnBEFORE_SALES_CREDIT_BALANCE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn THIS_RECEIPT_PRICEColumn {
                get {
                    return this.columnTHIS_RECEIPT_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn THIS_RECEIPT_PERCENTColumn {
                get {
                    return this.columnTHIS_RECEIPT_PERCENT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn THIS_SALES_PRICEColumn {
                get {
                    return this.columnTHIS_SALES_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn THIS_SALES_TAXColumn {
                get {
                    return this.columnTHIS_SALES_TAX;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn THIS_SALES_CREDIT_BALANCEColumn {
                get {
                    return this.columnTHIS_SALES_CREDIT_BALANCE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn THIS_CASH_PRICEColumn {
                get {
                    return this.columnTHIS_CASH_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn THIS_ACCOUNT_PRICEColumn {
                get {
                    return this.columnTHIS_ACCOUNT_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn THIS_COMMISSION_PRICEColumn {
                get {
                    return this.columnTHIS_COMMISSION_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn THIS_BILL_PRICEColumn {
                get {
                    return this.columnTHIS_BILL_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn THIS_ANOTHER_PRICEColumn {
                get {
                    return this.columnTHIS_ANOTHER_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn USER_NAMEColumn {
                get {
                    return this.columnUSER_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn GROUP_RANGEColumn {
                get {
                    return this.columnGROUP_RANGE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn STRING_WHERE1Column {
                get {
                    return this.columnSTRING_WHERE1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn STRING_WHERE2Column {
                get {
                    return this.columnSTRING_WHERE2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public SalesBalancePrintRow this[int index] {
                get {
                    return ((SalesBalancePrintRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event SalesBalancePrintRowChangeEventHandler SalesBalancePrintRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event SalesBalancePrintRowChangeEventHandler SalesBalancePrintRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event SalesBalancePrintRowChangeEventHandler SalesBalancePrintRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event SalesBalancePrintRowChangeEventHandler SalesBalancePrintRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddSalesBalancePrintRow(SalesBalancePrintRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public SalesBalancePrintRow AddSalesBalancePrintRow(
                        int COMPANY_ID, 
                        long GROUP_ID, 
                        string GROUP_SUM, 
                        string YM, 
                        string INVOICE_ID, 
                        string INVOICE_NAME, 
                        double SALES_CREDIT_INIT_PRICE, 
                        double SUM_NO_TAX_PRICE, 
                        double SUM_TAX, 
                        double SUM_PRICE, 
                        double BEFORE_SALES_CREDIT_BALANCE, 
                        double THIS_RECEIPT_PRICE, 
                        double THIS_RECEIPT_PERCENT, 
                        double THIS_SALES_PRICE, 
                        double THIS_SALES_TAX, 
                        double THIS_SALES_CREDIT_BALANCE, 
                        double THIS_CASH_PRICE, 
                        double THIS_ACCOUNT_PRICE, 
                        double THIS_COMMISSION_PRICE, 
                        double THIS_BILL_PRICE, 
                        double THIS_ANOTHER_PRICE, 
                        string USER_NAME, 
                        string GROUP_RANGE, 
                        string STRING_WHERE1, 
                        string STRING_WHERE2) {
                SalesBalancePrintRow rowSalesBalancePrintRow = ((SalesBalancePrintRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        COMPANY_ID,
                        GROUP_ID,
                        GROUP_SUM,
                        YM,
                        INVOICE_ID,
                        INVOICE_NAME,
                        SALES_CREDIT_INIT_PRICE,
                        SUM_NO_TAX_PRICE,
                        SUM_TAX,
                        SUM_PRICE,
                        BEFORE_SALES_CREDIT_BALANCE,
                        THIS_RECEIPT_PRICE,
                        THIS_RECEIPT_PERCENT,
                        THIS_SALES_PRICE,
                        THIS_SALES_TAX,
                        THIS_SALES_CREDIT_BALANCE,
                        THIS_CASH_PRICE,
                        THIS_ACCOUNT_PRICE,
                        THIS_COMMISSION_PRICE,
                        THIS_BILL_PRICE,
                        THIS_ANOTHER_PRICE,
                        USER_NAME,
                        GROUP_RANGE,
                        STRING_WHERE1,
                        STRING_WHERE2};
                rowSalesBalancePrintRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowSalesBalancePrintRow);
                return rowSalesBalancePrintRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                SalesBalancePrintDataTable cln = ((SalesBalancePrintDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new SalesBalancePrintDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnCOMPANY_ID = base.Columns["COMPANY_ID"];
                this.columnGROUP_ID = base.Columns["GROUP_ID"];
                this.columnGROUP_SUM = base.Columns["GROUP_SUM"];
                this.columnYM = base.Columns["YM"];
                this.columnINVOICE_ID = base.Columns["INVOICE_ID"];
                this.columnINVOICE_NAME = base.Columns["INVOICE_NAME"];
                this.columnSALES_CREDIT_INIT_PRICE = base.Columns["SALES_CREDIT_INIT_PRICE"];
                this.columnSUM_NO_TAX_PRICE = base.Columns["SUM_NO_TAX_PRICE"];
                this.columnSUM_TAX = base.Columns["SUM_TAX"];
                this.columnSUM_PRICE = base.Columns["SUM_PRICE"];
                this.columnBEFORE_SALES_CREDIT_BALANCE = base.Columns["BEFORE_SALES_CREDIT_BALANCE"];
                this.columnTHIS_RECEIPT_PRICE = base.Columns["THIS_RECEIPT_PRICE"];
                this.columnTHIS_RECEIPT_PERCENT = base.Columns["THIS_RECEIPT_PERCENT"];
                this.columnTHIS_SALES_PRICE = base.Columns["THIS_SALES_PRICE"];
                this.columnTHIS_SALES_TAX = base.Columns["THIS_SALES_TAX"];
                this.columnTHIS_SALES_CREDIT_BALANCE = base.Columns["THIS_SALES_CREDIT_BALANCE"];
                this.columnTHIS_CASH_PRICE = base.Columns["THIS_CASH_PRICE"];
                this.columnTHIS_ACCOUNT_PRICE = base.Columns["THIS_ACCOUNT_PRICE"];
                this.columnTHIS_COMMISSION_PRICE = base.Columns["THIS_COMMISSION_PRICE"];
                this.columnTHIS_BILL_PRICE = base.Columns["THIS_BILL_PRICE"];
                this.columnTHIS_ANOTHER_PRICE = base.Columns["THIS_ANOTHER_PRICE"];
                this.columnUSER_NAME = base.Columns["USER_NAME"];
                this.columnGROUP_RANGE = base.Columns["GROUP_RANGE"];
                this.columnSTRING_WHERE1 = base.Columns["STRING_WHERE1"];
                this.columnSTRING_WHERE2 = base.Columns["STRING_WHERE2"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnCOMPANY_ID = new global::System.Data.DataColumn("COMPANY_ID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOMPANY_ID);
                this.columnGROUP_ID = new global::System.Data.DataColumn("GROUP_ID", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGROUP_ID);
                this.columnGROUP_SUM = new global::System.Data.DataColumn("GROUP_SUM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGROUP_SUM);
                this.columnYM = new global::System.Data.DataColumn("YM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYM);
                this.columnINVOICE_ID = new global::System.Data.DataColumn("INVOICE_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINVOICE_ID);
                this.columnINVOICE_NAME = new global::System.Data.DataColumn("INVOICE_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINVOICE_NAME);
                this.columnSALES_CREDIT_INIT_PRICE = new global::System.Data.DataColumn("SALES_CREDIT_INIT_PRICE", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSALES_CREDIT_INIT_PRICE);
                this.columnSUM_NO_TAX_PRICE = new global::System.Data.DataColumn("SUM_NO_TAX_PRICE", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSUM_NO_TAX_PRICE);
                this.columnSUM_TAX = new global::System.Data.DataColumn("SUM_TAX", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSUM_TAX);
                this.columnSUM_PRICE = new global::System.Data.DataColumn("SUM_PRICE", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSUM_PRICE);
                this.columnBEFORE_SALES_CREDIT_BALANCE = new global::System.Data.DataColumn("BEFORE_SALES_CREDIT_BALANCE", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBEFORE_SALES_CREDIT_BALANCE);
                this.columnTHIS_RECEIPT_PRICE = new global::System.Data.DataColumn("THIS_RECEIPT_PRICE", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTHIS_RECEIPT_PRICE);
                this.columnTHIS_RECEIPT_PERCENT = new global::System.Data.DataColumn("THIS_RECEIPT_PERCENT", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTHIS_RECEIPT_PERCENT);
                this.columnTHIS_SALES_PRICE = new global::System.Data.DataColumn("THIS_SALES_PRICE", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTHIS_SALES_PRICE);
                this.columnTHIS_SALES_TAX = new global::System.Data.DataColumn("THIS_SALES_TAX", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTHIS_SALES_TAX);
                this.columnTHIS_SALES_CREDIT_BALANCE = new global::System.Data.DataColumn("THIS_SALES_CREDIT_BALANCE", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTHIS_SALES_CREDIT_BALANCE);
                this.columnTHIS_CASH_PRICE = new global::System.Data.DataColumn("THIS_CASH_PRICE", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTHIS_CASH_PRICE);
                this.columnTHIS_ACCOUNT_PRICE = new global::System.Data.DataColumn("THIS_ACCOUNT_PRICE", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTHIS_ACCOUNT_PRICE);
                this.columnTHIS_COMMISSION_PRICE = new global::System.Data.DataColumn("THIS_COMMISSION_PRICE", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTHIS_COMMISSION_PRICE);
                this.columnTHIS_BILL_PRICE = new global::System.Data.DataColumn("THIS_BILL_PRICE", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTHIS_BILL_PRICE);
                this.columnTHIS_ANOTHER_PRICE = new global::System.Data.DataColumn("THIS_ANOTHER_PRICE", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTHIS_ANOTHER_PRICE);
                this.columnUSER_NAME = new global::System.Data.DataColumn("USER_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_NAME);
                this.columnGROUP_RANGE = new global::System.Data.DataColumn("GROUP_RANGE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGROUP_RANGE);
                this.columnSTRING_WHERE1 = new global::System.Data.DataColumn("STRING_WHERE1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTRING_WHERE1);
                this.columnSTRING_WHERE2 = new global::System.Data.DataColumn("STRING_WHERE2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTRING_WHERE2);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public SalesBalancePrintRow NewSalesBalancePrintRow() {
                return ((SalesBalancePrintRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new SalesBalancePrintRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(SalesBalancePrintRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SalesBalancePrintRowChanged != null)) {
                    this.SalesBalancePrintRowChanged(this, new SalesBalancePrintRowChangeEvent(((SalesBalancePrintRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SalesBalancePrintRowChanging != null)) {
                    this.SalesBalancePrintRowChanging(this, new SalesBalancePrintRowChangeEvent(((SalesBalancePrintRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SalesBalancePrintRowDeleted != null)) {
                    this.SalesBalancePrintRowDeleted(this, new SalesBalancePrintRowChangeEvent(((SalesBalancePrintRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SalesBalancePrintRowDeleting != null)) {
                    this.SalesBalancePrintRowDeleting(this, new SalesBalancePrintRowChangeEvent(((SalesBalancePrintRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveSalesBalancePrintRow(SalesBalancePrintRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                _SalesBalancePrint ds = new _SalesBalancePrint();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "SalesBalancePrintDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class SalesBalancePrintRow : global::System.Data.DataRow {
            
            private SalesBalancePrintDataTable tableSalesBalancePrint;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal SalesBalancePrintRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableSalesBalancePrint = ((SalesBalancePrintDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int COMPANY_ID {
                get {
                    try {
                        return ((int)(this[this.tableSalesBalancePrint.COMPANY_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'COMPANY_ID\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.COMPANY_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public long GROUP_ID {
                get {
                    try {
                        return ((long)(this[this.tableSalesBalancePrint.GROUP_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'GROUP_ID\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.GROUP_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string GROUP_SUM {
                get {
                    try {
                        return ((string)(this[this.tableSalesBalancePrint.GROUP_SUMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'GROUP_SUM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.GROUP_SUMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string YM {
                get {
                    try {
                        return ((string)(this[this.tableSalesBalancePrint.YMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'YM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.YMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string INVOICE_ID {
                get {
                    try {
                        return ((string)(this[this.tableSalesBalancePrint.INVOICE_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'INVOICE_ID\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.INVOICE_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string INVOICE_NAME {
                get {
                    try {
                        return ((string)(this[this.tableSalesBalancePrint.INVOICE_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'INVOICE_NAME\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.INVOICE_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double SALES_CREDIT_INIT_PRICE {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.SALES_CREDIT_INIT_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'SALES_CREDIT_INIT_PRICE\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.SALES_CREDIT_INIT_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double SUM_NO_TAX_PRICE {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.SUM_NO_TAX_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'SUM_NO_TAX_PRICE\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.SUM_NO_TAX_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double SUM_TAX {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.SUM_TAXColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'SUM_TAX\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.SUM_TAXColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double SUM_PRICE {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.SUM_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'SUM_PRICE\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.SUM_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double BEFORE_SALES_CREDIT_BALANCE {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.BEFORE_SALES_CREDIT_BALANCEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'BEFORE_SALES_CREDIT_BALANCE\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.BEFORE_SALES_CREDIT_BALANCEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double THIS_RECEIPT_PRICE {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.THIS_RECEIPT_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'THIS_RECEIPT_PRICE\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.THIS_RECEIPT_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double THIS_RECEIPT_PERCENT {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.THIS_RECEIPT_PERCENTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'THIS_RECEIPT_PERCENT\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.THIS_RECEIPT_PERCENTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double THIS_SALES_PRICE {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.THIS_SALES_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'THIS_SALES_PRICE\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.THIS_SALES_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double THIS_SALES_TAX {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.THIS_SALES_TAXColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'THIS_SALES_TAX\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.THIS_SALES_TAXColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double THIS_SALES_CREDIT_BALANCE {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.THIS_SALES_CREDIT_BALANCEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'THIS_SALES_CREDIT_BALANCE\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.THIS_SALES_CREDIT_BALANCEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double THIS_CASH_PRICE {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.THIS_CASH_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'THIS_CASH_PRICE\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.THIS_CASH_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double THIS_ACCOUNT_PRICE {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.THIS_ACCOUNT_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'THIS_ACCOUNT_PRICE\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.THIS_ACCOUNT_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double THIS_COMMISSION_PRICE {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.THIS_COMMISSION_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'THIS_COMMISSION_PRICE\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.THIS_COMMISSION_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double THIS_BILL_PRICE {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.THIS_BILL_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'THIS_BILL_PRICE\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.THIS_BILL_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double THIS_ANOTHER_PRICE {
                get {
                    try {
                        return ((double)(this[this.tableSalesBalancePrint.THIS_ANOTHER_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'THIS_ANOTHER_PRICE\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.THIS_ANOTHER_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string USER_NAME {
                get {
                    try {
                        return ((string)(this[this.tableSalesBalancePrint.USER_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'USER_NAME\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.USER_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string GROUP_RANGE {
                get {
                    try {
                        return ((string)(this[this.tableSalesBalancePrint.GROUP_RANGEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'GROUP_RANGE\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.GROUP_RANGEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string STRING_WHERE1 {
                get {
                    try {
                        return ((string)(this[this.tableSalesBalancePrint.STRING_WHERE1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'STRING_WHERE1\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.STRING_WHERE1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string STRING_WHERE2 {
                get {
                    try {
                        return ((string)(this[this.tableSalesBalancePrint.STRING_WHERE2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'SalesBalancePrint\' にある列 \'STRING_WHERE2\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableSalesBalancePrint.STRING_WHERE2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCOMPANY_IDNull() {
                return this.IsNull(this.tableSalesBalancePrint.COMPANY_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCOMPANY_IDNull() {
                this[this.tableSalesBalancePrint.COMPANY_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsGROUP_IDNull() {
                return this.IsNull(this.tableSalesBalancePrint.GROUP_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetGROUP_IDNull() {
                this[this.tableSalesBalancePrint.GROUP_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsGROUP_SUMNull() {
                return this.IsNull(this.tableSalesBalancePrint.GROUP_SUMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetGROUP_SUMNull() {
                this[this.tableSalesBalancePrint.GROUP_SUMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsYMNull() {
                return this.IsNull(this.tableSalesBalancePrint.YMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetYMNull() {
                this[this.tableSalesBalancePrint.YMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsINVOICE_IDNull() {
                return this.IsNull(this.tableSalesBalancePrint.INVOICE_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetINVOICE_IDNull() {
                this[this.tableSalesBalancePrint.INVOICE_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsINVOICE_NAMENull() {
                return this.IsNull(this.tableSalesBalancePrint.INVOICE_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetINVOICE_NAMENull() {
                this[this.tableSalesBalancePrint.INVOICE_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSALES_CREDIT_INIT_PRICENull() {
                return this.IsNull(this.tableSalesBalancePrint.SALES_CREDIT_INIT_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSALES_CREDIT_INIT_PRICENull() {
                this[this.tableSalesBalancePrint.SALES_CREDIT_INIT_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSUM_NO_TAX_PRICENull() {
                return this.IsNull(this.tableSalesBalancePrint.SUM_NO_TAX_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSUM_NO_TAX_PRICENull() {
                this[this.tableSalesBalancePrint.SUM_NO_TAX_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSUM_TAXNull() {
                return this.IsNull(this.tableSalesBalancePrint.SUM_TAXColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSUM_TAXNull() {
                this[this.tableSalesBalancePrint.SUM_TAXColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSUM_PRICENull() {
                return this.IsNull(this.tableSalesBalancePrint.SUM_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSUM_PRICENull() {
                this[this.tableSalesBalancePrint.SUM_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBEFORE_SALES_CREDIT_BALANCENull() {
                return this.IsNull(this.tableSalesBalancePrint.BEFORE_SALES_CREDIT_BALANCEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBEFORE_SALES_CREDIT_BALANCENull() {
                this[this.tableSalesBalancePrint.BEFORE_SALES_CREDIT_BALANCEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTHIS_RECEIPT_PRICENull() {
                return this.IsNull(this.tableSalesBalancePrint.THIS_RECEIPT_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTHIS_RECEIPT_PRICENull() {
                this[this.tableSalesBalancePrint.THIS_RECEIPT_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTHIS_RECEIPT_PERCENTNull() {
                return this.IsNull(this.tableSalesBalancePrint.THIS_RECEIPT_PERCENTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTHIS_RECEIPT_PERCENTNull() {
                this[this.tableSalesBalancePrint.THIS_RECEIPT_PERCENTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTHIS_SALES_PRICENull() {
                return this.IsNull(this.tableSalesBalancePrint.THIS_SALES_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTHIS_SALES_PRICENull() {
                this[this.tableSalesBalancePrint.THIS_SALES_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTHIS_SALES_TAXNull() {
                return this.IsNull(this.tableSalesBalancePrint.THIS_SALES_TAXColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTHIS_SALES_TAXNull() {
                this[this.tableSalesBalancePrint.THIS_SALES_TAXColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTHIS_SALES_CREDIT_BALANCENull() {
                return this.IsNull(this.tableSalesBalancePrint.THIS_SALES_CREDIT_BALANCEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTHIS_SALES_CREDIT_BALANCENull() {
                this[this.tableSalesBalancePrint.THIS_SALES_CREDIT_BALANCEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTHIS_CASH_PRICENull() {
                return this.IsNull(this.tableSalesBalancePrint.THIS_CASH_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTHIS_CASH_PRICENull() {
                this[this.tableSalesBalancePrint.THIS_CASH_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTHIS_ACCOUNT_PRICENull() {
                return this.IsNull(this.tableSalesBalancePrint.THIS_ACCOUNT_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTHIS_ACCOUNT_PRICENull() {
                this[this.tableSalesBalancePrint.THIS_ACCOUNT_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTHIS_COMMISSION_PRICENull() {
                return this.IsNull(this.tableSalesBalancePrint.THIS_COMMISSION_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTHIS_COMMISSION_PRICENull() {
                this[this.tableSalesBalancePrint.THIS_COMMISSION_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTHIS_BILL_PRICENull() {
                return this.IsNull(this.tableSalesBalancePrint.THIS_BILL_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTHIS_BILL_PRICENull() {
                this[this.tableSalesBalancePrint.THIS_BILL_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTHIS_ANOTHER_PRICENull() {
                return this.IsNull(this.tableSalesBalancePrint.THIS_ANOTHER_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTHIS_ANOTHER_PRICENull() {
                this[this.tableSalesBalancePrint.THIS_ANOTHER_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsUSER_NAMENull() {
                return this.IsNull(this.tableSalesBalancePrint.USER_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetUSER_NAMENull() {
                this[this.tableSalesBalancePrint.USER_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsGROUP_RANGENull() {
                return this.IsNull(this.tableSalesBalancePrint.GROUP_RANGEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetGROUP_RANGENull() {
                this[this.tableSalesBalancePrint.GROUP_RANGEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSTRING_WHERE1Null() {
                return this.IsNull(this.tableSalesBalancePrint.STRING_WHERE1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSTRING_WHERE1Null() {
                this[this.tableSalesBalancePrint.STRING_WHERE1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSTRING_WHERE2Null() {
                return this.IsNull(this.tableSalesBalancePrint.STRING_WHERE2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSTRING_WHERE2Null() {
                this[this.tableSalesBalancePrint.STRING_WHERE2Column] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class SalesBalancePrintRowChangeEvent : global::System.EventArgs {
            
            private SalesBalancePrintRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public SalesBalancePrintRowChangeEvent(SalesBalancePrintRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public SalesBalancePrintRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591