//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.237
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace SlvHanbaiClient.svcSales {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/SlvHanbai.Web.Class.Entity")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SlvHanbaiClient.svcSales.EntitySalesD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SlvHanbaiClient.svcSales.EntitySales))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SlvHanbaiClient.svcSales.EntitySalesH))]
    public partial class EntityBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntitySalesD", Namespace="http://schemas.datacontract.org/2004/07/SlvHanbai.Web.Class.Entity")]
    public partial class EntitySalesD : SlvHanbaiClient.svcSales.EntityBase {
        
        private int _breakdown_idField;
        
        private string _breakdown_nmField;
        
        private double _case_numberField;
        
        private string _commodity_idField;
        
        private string _commodity_nameField;
        
        private int _deliver_division_idField;
        
        private string _deliver_division_nmField;
        
        private double _enter_numberField;
        
        private long _idField;
        
        private int _inventory_management_division_idField;
        
        private double _inventory_numberField;
        
        private int _lock_flgField;
        
        private string _memoField;
        
        private string _messageField;
        
        private double _no_tax_priceField;
        
        private double _numberField;
        
        private int _number_decimal_digitField;
        
        private double _order_idField;
        
        private double _order_numberField;
        
        private double _order_stay_numberField;
        
        private double _priceField;
        
        private double _profitsField;
        
        private double _profits_percentField;
        
        private int _rec_noField;
        
        private double _retail_price_before_taxField;
        
        private double _retail_price_skip_taxField;
        
        private double _sales_costField;
        
        private double _sales_cost_price_before_taxField;
        
        private double _sales_cost_price_skip_taxField;
        
        private double _sales_unit_price_before_taxField;
        
        private double _sales_unit_price_skip_taxField;
        
        private double _taxField;
        
        private int _tax_division_idField;
        
        private string _tax_division_nmField;
        
        private int _tax_percentField;
        
        private int _unit_decimal_digitField;
        
        private int _unit_idField;
        
        private string _unit_nmField;
        
        private double _unit_priceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _breakdown_id {
            get {
                return this._breakdown_idField;
            }
            set {
                if ((this._breakdown_idField.Equals(value) != true)) {
                    this._breakdown_idField = value;
                    this.RaisePropertyChanged("_breakdown_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _breakdown_nm {
            get {
                return this._breakdown_nmField;
            }
            set {
                if ((object.ReferenceEquals(this._breakdown_nmField, value) != true)) {
                    this._breakdown_nmField = value;
                    this.RaisePropertyChanged("_breakdown_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _case_number {
            get {
                return this._case_numberField;
            }
            set {
                if ((this._case_numberField.Equals(value) != true)) {
                    this._case_numberField = value;
                    this.RaisePropertyChanged("_case_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _commodity_id {
            get {
                return this._commodity_idField;
            }
            set {
                if ((object.ReferenceEquals(this._commodity_idField, value) != true)) {
                    this._commodity_idField = value;
                    this.RaisePropertyChanged("_commodity_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _commodity_name {
            get {
                return this._commodity_nameField;
            }
            set {
                if ((object.ReferenceEquals(this._commodity_nameField, value) != true)) {
                    this._commodity_nameField = value;
                    this.RaisePropertyChanged("_commodity_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _deliver_division_id {
            get {
                return this._deliver_division_idField;
            }
            set {
                if ((this._deliver_division_idField.Equals(value) != true)) {
                    this._deliver_division_idField = value;
                    this.RaisePropertyChanged("_deliver_division_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _deliver_division_nm {
            get {
                return this._deliver_division_nmField;
            }
            set {
                if ((object.ReferenceEquals(this._deliver_division_nmField, value) != true)) {
                    this._deliver_division_nmField = value;
                    this.RaisePropertyChanged("_deliver_division_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _enter_number {
            get {
                return this._enter_numberField;
            }
            set {
                if ((this._enter_numberField.Equals(value) != true)) {
                    this._enter_numberField = value;
                    this.RaisePropertyChanged("_enter_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _inventory_management_division_id {
            get {
                return this._inventory_management_division_idField;
            }
            set {
                if ((this._inventory_management_division_idField.Equals(value) != true)) {
                    this._inventory_management_division_idField = value;
                    this.RaisePropertyChanged("_inventory_management_division_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _inventory_number {
            get {
                return this._inventory_numberField;
            }
            set {
                if ((this._inventory_numberField.Equals(value) != true)) {
                    this._inventory_numberField = value;
                    this.RaisePropertyChanged("_inventory_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _lock_flg {
            get {
                return this._lock_flgField;
            }
            set {
                if ((this._lock_flgField.Equals(value) != true)) {
                    this._lock_flgField = value;
                    this.RaisePropertyChanged("_lock_flg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _memo {
            get {
                return this._memoField;
            }
            set {
                if ((object.ReferenceEquals(this._memoField, value) != true)) {
                    this._memoField = value;
                    this.RaisePropertyChanged("_memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _message {
            get {
                return this._messageField;
            }
            set {
                if ((object.ReferenceEquals(this._messageField, value) != true)) {
                    this._messageField = value;
                    this.RaisePropertyChanged("_message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _no_tax_price {
            get {
                return this._no_tax_priceField;
            }
            set {
                if ((this._no_tax_priceField.Equals(value) != true)) {
                    this._no_tax_priceField = value;
                    this.RaisePropertyChanged("_no_tax_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _number {
            get {
                return this._numberField;
            }
            set {
                if ((this._numberField.Equals(value) != true)) {
                    this._numberField = value;
                    this.RaisePropertyChanged("_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _number_decimal_digit {
            get {
                return this._number_decimal_digitField;
            }
            set {
                if ((this._number_decimal_digitField.Equals(value) != true)) {
                    this._number_decimal_digitField = value;
                    this.RaisePropertyChanged("_number_decimal_digit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _order_id {
            get {
                return this._order_idField;
            }
            set {
                if ((this._order_idField.Equals(value) != true)) {
                    this._order_idField = value;
                    this.RaisePropertyChanged("_order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _order_number {
            get {
                return this._order_numberField;
            }
            set {
                if ((this._order_numberField.Equals(value) != true)) {
                    this._order_numberField = value;
                    this.RaisePropertyChanged("_order_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _order_stay_number {
            get {
                return this._order_stay_numberField;
            }
            set {
                if ((this._order_stay_numberField.Equals(value) != true)) {
                    this._order_stay_numberField = value;
                    this.RaisePropertyChanged("_order_stay_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _price {
            get {
                return this._priceField;
            }
            set {
                if ((this._priceField.Equals(value) != true)) {
                    this._priceField = value;
                    this.RaisePropertyChanged("_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _profits {
            get {
                return this._profitsField;
            }
            set {
                if ((this._profitsField.Equals(value) != true)) {
                    this._profitsField = value;
                    this.RaisePropertyChanged("_profits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _profits_percent {
            get {
                return this._profits_percentField;
            }
            set {
                if ((this._profits_percentField.Equals(value) != true)) {
                    this._profits_percentField = value;
                    this.RaisePropertyChanged("_profits_percent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _rec_no {
            get {
                return this._rec_noField;
            }
            set {
                if ((this._rec_noField.Equals(value) != true)) {
                    this._rec_noField = value;
                    this.RaisePropertyChanged("_rec_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _retail_price_before_tax {
            get {
                return this._retail_price_before_taxField;
            }
            set {
                if ((this._retail_price_before_taxField.Equals(value) != true)) {
                    this._retail_price_before_taxField = value;
                    this.RaisePropertyChanged("_retail_price_before_tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _retail_price_skip_tax {
            get {
                return this._retail_price_skip_taxField;
            }
            set {
                if ((this._retail_price_skip_taxField.Equals(value) != true)) {
                    this._retail_price_skip_taxField = value;
                    this.RaisePropertyChanged("_retail_price_skip_tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sales_cost {
            get {
                return this._sales_costField;
            }
            set {
                if ((this._sales_costField.Equals(value) != true)) {
                    this._sales_costField = value;
                    this.RaisePropertyChanged("_sales_cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sales_cost_price_before_tax {
            get {
                return this._sales_cost_price_before_taxField;
            }
            set {
                if ((this._sales_cost_price_before_taxField.Equals(value) != true)) {
                    this._sales_cost_price_before_taxField = value;
                    this.RaisePropertyChanged("_sales_cost_price_before_tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sales_cost_price_skip_tax {
            get {
                return this._sales_cost_price_skip_taxField;
            }
            set {
                if ((this._sales_cost_price_skip_taxField.Equals(value) != true)) {
                    this._sales_cost_price_skip_taxField = value;
                    this.RaisePropertyChanged("_sales_cost_price_skip_tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sales_unit_price_before_tax {
            get {
                return this._sales_unit_price_before_taxField;
            }
            set {
                if ((this._sales_unit_price_before_taxField.Equals(value) != true)) {
                    this._sales_unit_price_before_taxField = value;
                    this.RaisePropertyChanged("_sales_unit_price_before_tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sales_unit_price_skip_tax {
            get {
                return this._sales_unit_price_skip_taxField;
            }
            set {
                if ((this._sales_unit_price_skip_taxField.Equals(value) != true)) {
                    this._sales_unit_price_skip_taxField = value;
                    this.RaisePropertyChanged("_sales_unit_price_skip_tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _tax {
            get {
                return this._taxField;
            }
            set {
                if ((this._taxField.Equals(value) != true)) {
                    this._taxField = value;
                    this.RaisePropertyChanged("_tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _tax_division_id {
            get {
                return this._tax_division_idField;
            }
            set {
                if ((this._tax_division_idField.Equals(value) != true)) {
                    this._tax_division_idField = value;
                    this.RaisePropertyChanged("_tax_division_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _tax_division_nm {
            get {
                return this._tax_division_nmField;
            }
            set {
                if ((object.ReferenceEquals(this._tax_division_nmField, value) != true)) {
                    this._tax_division_nmField = value;
                    this.RaisePropertyChanged("_tax_division_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _tax_percent {
            get {
                return this._tax_percentField;
            }
            set {
                if ((this._tax_percentField.Equals(value) != true)) {
                    this._tax_percentField = value;
                    this.RaisePropertyChanged("_tax_percent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _unit_decimal_digit {
            get {
                return this._unit_decimal_digitField;
            }
            set {
                if ((this._unit_decimal_digitField.Equals(value) != true)) {
                    this._unit_decimal_digitField = value;
                    this.RaisePropertyChanged("_unit_decimal_digit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _unit_id {
            get {
                return this._unit_idField;
            }
            set {
                if ((this._unit_idField.Equals(value) != true)) {
                    this._unit_idField = value;
                    this.RaisePropertyChanged("_unit_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _unit_nm {
            get {
                return this._unit_nmField;
            }
            set {
                if ((object.ReferenceEquals(this._unit_nmField, value) != true)) {
                    this._unit_nmField = value;
                    this.RaisePropertyChanged("_unit_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _unit_price {
            get {
                return this._unit_priceField;
            }
            set {
                if ((this._unit_priceField.Equals(value) != true)) {
                    this._unit_priceField = value;
                    this.RaisePropertyChanged("_unit_price");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntitySales", Namespace="http://schemas.datacontract.org/2004/07/SlvHanbai.Web.Class.Entity")]
    public partial class EntitySales : SlvHanbaiClient.svcSales.EntityBase {
        
        private int breakdown_idField;
        
        private string breakdown_nmField;
        
        private int business_division_idField;
        
        private string business_division_nmField;
        
        private string commodity_idField;
        
        private string commodity_nameField;
        
        private string customer_idField;
        
        private string customer_nmField;
        
        private string d_memoField;
        
        private int deliver_division_idField;
        
        private string deliver_division_nmField;
        
        private double enter_numberField;
        
        private long estimatenoField;
        
        private long idField;
        
        private int input_personField;
        
        private string input_person_nmField;
        
        private string memoField;
        
        private string messageField;
        
        private long noField;
        
        private double numberField;
        
        private long order_noField;
        
        private double priceField;
        
        private int rec_noField;
        
        private string sales_ymdField;
        
        private string supplier_idField;
        
        private string supplier_nmField;
        
        private string supply_ymdField;
        
        private int tax_change_idField;
        
        private string tax_change_nmField;
        
        private int unit_idField;
        
        private string unit_nmField;
        
        private double unit_priceField;
        
        private int update_person_idField;
        
        private string update_person_nmField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int breakdown_id {
            get {
                return this.breakdown_idField;
            }
            set {
                if ((this.breakdown_idField.Equals(value) != true)) {
                    this.breakdown_idField = value;
                    this.RaisePropertyChanged("breakdown_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string breakdown_nm {
            get {
                return this.breakdown_nmField;
            }
            set {
                if ((object.ReferenceEquals(this.breakdown_nmField, value) != true)) {
                    this.breakdown_nmField = value;
                    this.RaisePropertyChanged("breakdown_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int business_division_id {
            get {
                return this.business_division_idField;
            }
            set {
                if ((this.business_division_idField.Equals(value) != true)) {
                    this.business_division_idField = value;
                    this.RaisePropertyChanged("business_division_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string business_division_nm {
            get {
                return this.business_division_nmField;
            }
            set {
                if ((object.ReferenceEquals(this.business_division_nmField, value) != true)) {
                    this.business_division_nmField = value;
                    this.RaisePropertyChanged("business_division_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string commodity_id {
            get {
                return this.commodity_idField;
            }
            set {
                if ((object.ReferenceEquals(this.commodity_idField, value) != true)) {
                    this.commodity_idField = value;
                    this.RaisePropertyChanged("commodity_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string commodity_name {
            get {
                return this.commodity_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.commodity_nameField, value) != true)) {
                    this.commodity_nameField = value;
                    this.RaisePropertyChanged("commodity_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customer_id {
            get {
                return this.customer_idField;
            }
            set {
                if ((object.ReferenceEquals(this.customer_idField, value) != true)) {
                    this.customer_idField = value;
                    this.RaisePropertyChanged("customer_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customer_nm {
            get {
                return this.customer_nmField;
            }
            set {
                if ((object.ReferenceEquals(this.customer_nmField, value) != true)) {
                    this.customer_nmField = value;
                    this.RaisePropertyChanged("customer_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string d_memo {
            get {
                return this.d_memoField;
            }
            set {
                if ((object.ReferenceEquals(this.d_memoField, value) != true)) {
                    this.d_memoField = value;
                    this.RaisePropertyChanged("d_memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int deliver_division_id {
            get {
                return this.deliver_division_idField;
            }
            set {
                if ((this.deliver_division_idField.Equals(value) != true)) {
                    this.deliver_division_idField = value;
                    this.RaisePropertyChanged("deliver_division_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deliver_division_nm {
            get {
                return this.deliver_division_nmField;
            }
            set {
                if ((object.ReferenceEquals(this.deliver_division_nmField, value) != true)) {
                    this.deliver_division_nmField = value;
                    this.RaisePropertyChanged("deliver_division_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double enter_number {
            get {
                return this.enter_numberField;
            }
            set {
                if ((this.enter_numberField.Equals(value) != true)) {
                    this.enter_numberField = value;
                    this.RaisePropertyChanged("enter_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long estimateno {
            get {
                return this.estimatenoField;
            }
            set {
                if ((this.estimatenoField.Equals(value) != true)) {
                    this.estimatenoField = value;
                    this.RaisePropertyChanged("estimateno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int input_person {
            get {
                return this.input_personField;
            }
            set {
                if ((this.input_personField.Equals(value) != true)) {
                    this.input_personField = value;
                    this.RaisePropertyChanged("input_person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string input_person_nm {
            get {
                return this.input_person_nmField;
            }
            set {
                if ((object.ReferenceEquals(this.input_person_nmField, value) != true)) {
                    this.input_person_nmField = value;
                    this.RaisePropertyChanged("input_person_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string memo {
            get {
                return this.memoField;
            }
            set {
                if ((object.ReferenceEquals(this.memoField, value) != true)) {
                    this.memoField = value;
                    this.RaisePropertyChanged("memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long no {
            get {
                return this.noField;
            }
            set {
                if ((this.noField.Equals(value) != true)) {
                    this.noField = value;
                    this.RaisePropertyChanged("no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long order_no {
            get {
                return this.order_noField;
            }
            set {
                if ((this.order_noField.Equals(value) != true)) {
                    this.order_noField = value;
                    this.RaisePropertyChanged("order_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rec_no {
            get {
                return this.rec_noField;
            }
            set {
                if ((this.rec_noField.Equals(value) != true)) {
                    this.rec_noField = value;
                    this.RaisePropertyChanged("rec_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sales_ymd {
            get {
                return this.sales_ymdField;
            }
            set {
                if ((object.ReferenceEquals(this.sales_ymdField, value) != true)) {
                    this.sales_ymdField = value;
                    this.RaisePropertyChanged("sales_ymd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string supplier_id {
            get {
                return this.supplier_idField;
            }
            set {
                if ((object.ReferenceEquals(this.supplier_idField, value) != true)) {
                    this.supplier_idField = value;
                    this.RaisePropertyChanged("supplier_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string supplier_nm {
            get {
                return this.supplier_nmField;
            }
            set {
                if ((object.ReferenceEquals(this.supplier_nmField, value) != true)) {
                    this.supplier_nmField = value;
                    this.RaisePropertyChanged("supplier_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string supply_ymd {
            get {
                return this.supply_ymdField;
            }
            set {
                if ((object.ReferenceEquals(this.supply_ymdField, value) != true)) {
                    this.supply_ymdField = value;
                    this.RaisePropertyChanged("supply_ymd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tax_change_id {
            get {
                return this.tax_change_idField;
            }
            set {
                if ((this.tax_change_idField.Equals(value) != true)) {
                    this.tax_change_idField = value;
                    this.RaisePropertyChanged("tax_change_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tax_change_nm {
            get {
                return this.tax_change_nmField;
            }
            set {
                if ((object.ReferenceEquals(this.tax_change_nmField, value) != true)) {
                    this.tax_change_nmField = value;
                    this.RaisePropertyChanged("tax_change_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int unit_id {
            get {
                return this.unit_idField;
            }
            set {
                if ((this.unit_idField.Equals(value) != true)) {
                    this.unit_idField = value;
                    this.RaisePropertyChanged("unit_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unit_nm {
            get {
                return this.unit_nmField;
            }
            set {
                if ((object.ReferenceEquals(this.unit_nmField, value) != true)) {
                    this.unit_nmField = value;
                    this.RaisePropertyChanged("unit_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double unit_price {
            get {
                return this.unit_priceField;
            }
            set {
                if ((this.unit_priceField.Equals(value) != true)) {
                    this.unit_priceField = value;
                    this.RaisePropertyChanged("unit_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int update_person_id {
            get {
                return this.update_person_idField;
            }
            set {
                if ((this.update_person_idField.Equals(value) != true)) {
                    this.update_person_idField = value;
                    this.RaisePropertyChanged("update_person_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string update_person_nm {
            get {
                return this.update_person_nmField;
            }
            set {
                if ((object.ReferenceEquals(this.update_person_nmField, value) != true)) {
                    this.update_person_nmField = value;
                    this.RaisePropertyChanged("update_person_nm");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntitySalesH", Namespace="http://schemas.datacontract.org/2004/07/SlvHanbai.Web.Class.Entity")]
    public partial class EntitySalesH : SlvHanbaiClient.svcSales.EntityBase {
        
        private double _before_sales_credit_priceField;
        
        private int _business_division_idField;
        
        private string _business_division_nameField;
        
        private int _collect_cycle_idField;
        
        private int _collect_dayField;
        
        private double _credit_limit_priceField;
        
        private int _credit_rateField;
        
        private string _customer_idField;
        
        private string _customer_nameField;
        
        private long _estimatenoField;
        
        private long _idField;
        
        private int _invoice_close_flgField;
        
        private string _invoice_idField;
        
        private string _invoice_nameField;
        
        private long _invoice_noField;
        
        private string _invoice_stateField;
        
        private string _invoice_yyyymmddField;
        
        private int _lock_flgField;
        
        private string _memoField;
        
        private string _messageField;
        
        private long _noField;
        
        private long _order_noField;
        
        private int _price_fraction_proc_idField;
        
        private double _profits_percentField;
        
        private int _receipt_receivable_kbnField;
        
        private string _receipt_receivable_kbn_nmField;
        
        private long _red_before_noField;
        
        private double _sales_credit_priceField;
        
        private string _sales_ymdField;
        
        private double _sum_case_numberField;
        
        private double _sum_enter_numberField;
        
        private double _sum_no_tax_priceField;
        
        private double _sum_numberField;
        
        private double _sum_priceField;
        
        private double _sum_profitsField;
        
        private double _sum_sales_costField;
        
        private double _sum_taxField;
        
        private double _sum_unit_priceField;
        
        private string _supplier_idField;
        
        private string _supplier_nameField;
        
        private string _supply_ymdField;
        
        private int _tax_change_idField;
        
        private string _tax_change_nameField;
        
        private int _tax_fraction_proc_idField;
        
        private int _unit_kind_idField;
        
        private string _update_dateField;
        
        private int _update_flgField;
        
        private int _update_person_idField;
        
        private string _update_person_nmField;
        
        private System.DateTime _update_timeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _before_sales_credit_price {
            get {
                return this._before_sales_credit_priceField;
            }
            set {
                if ((this._before_sales_credit_priceField.Equals(value) != true)) {
                    this._before_sales_credit_priceField = value;
                    this.RaisePropertyChanged("_before_sales_credit_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _business_division_id {
            get {
                return this._business_division_idField;
            }
            set {
                if ((this._business_division_idField.Equals(value) != true)) {
                    this._business_division_idField = value;
                    this.RaisePropertyChanged("_business_division_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _business_division_name {
            get {
                return this._business_division_nameField;
            }
            set {
                if ((object.ReferenceEquals(this._business_division_nameField, value) != true)) {
                    this._business_division_nameField = value;
                    this.RaisePropertyChanged("_business_division_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _collect_cycle_id {
            get {
                return this._collect_cycle_idField;
            }
            set {
                if ((this._collect_cycle_idField.Equals(value) != true)) {
                    this._collect_cycle_idField = value;
                    this.RaisePropertyChanged("_collect_cycle_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _collect_day {
            get {
                return this._collect_dayField;
            }
            set {
                if ((this._collect_dayField.Equals(value) != true)) {
                    this._collect_dayField = value;
                    this.RaisePropertyChanged("_collect_day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _credit_limit_price {
            get {
                return this._credit_limit_priceField;
            }
            set {
                if ((this._credit_limit_priceField.Equals(value) != true)) {
                    this._credit_limit_priceField = value;
                    this.RaisePropertyChanged("_credit_limit_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _credit_rate {
            get {
                return this._credit_rateField;
            }
            set {
                if ((this._credit_rateField.Equals(value) != true)) {
                    this._credit_rateField = value;
                    this.RaisePropertyChanged("_credit_rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _customer_id {
            get {
                return this._customer_idField;
            }
            set {
                if ((object.ReferenceEquals(this._customer_idField, value) != true)) {
                    this._customer_idField = value;
                    this.RaisePropertyChanged("_customer_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _customer_name {
            get {
                return this._customer_nameField;
            }
            set {
                if ((object.ReferenceEquals(this._customer_nameField, value) != true)) {
                    this._customer_nameField = value;
                    this.RaisePropertyChanged("_customer_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _estimateno {
            get {
                return this._estimatenoField;
            }
            set {
                if ((this._estimatenoField.Equals(value) != true)) {
                    this._estimatenoField = value;
                    this.RaisePropertyChanged("_estimateno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _invoice_close_flg {
            get {
                return this._invoice_close_flgField;
            }
            set {
                if ((this._invoice_close_flgField.Equals(value) != true)) {
                    this._invoice_close_flgField = value;
                    this.RaisePropertyChanged("_invoice_close_flg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _invoice_id {
            get {
                return this._invoice_idField;
            }
            set {
                if ((object.ReferenceEquals(this._invoice_idField, value) != true)) {
                    this._invoice_idField = value;
                    this.RaisePropertyChanged("_invoice_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _invoice_name {
            get {
                return this._invoice_nameField;
            }
            set {
                if ((object.ReferenceEquals(this._invoice_nameField, value) != true)) {
                    this._invoice_nameField = value;
                    this.RaisePropertyChanged("_invoice_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _invoice_no {
            get {
                return this._invoice_noField;
            }
            set {
                if ((this._invoice_noField.Equals(value) != true)) {
                    this._invoice_noField = value;
                    this.RaisePropertyChanged("_invoice_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _invoice_state {
            get {
                return this._invoice_stateField;
            }
            set {
                if ((object.ReferenceEquals(this._invoice_stateField, value) != true)) {
                    this._invoice_stateField = value;
                    this.RaisePropertyChanged("_invoice_state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _invoice_yyyymmdd {
            get {
                return this._invoice_yyyymmddField;
            }
            set {
                if ((object.ReferenceEquals(this._invoice_yyyymmddField, value) != true)) {
                    this._invoice_yyyymmddField = value;
                    this.RaisePropertyChanged("_invoice_yyyymmdd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _lock_flg {
            get {
                return this._lock_flgField;
            }
            set {
                if ((this._lock_flgField.Equals(value) != true)) {
                    this._lock_flgField = value;
                    this.RaisePropertyChanged("_lock_flg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _memo {
            get {
                return this._memoField;
            }
            set {
                if ((object.ReferenceEquals(this._memoField, value) != true)) {
                    this._memoField = value;
                    this.RaisePropertyChanged("_memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _message {
            get {
                return this._messageField;
            }
            set {
                if ((object.ReferenceEquals(this._messageField, value) != true)) {
                    this._messageField = value;
                    this.RaisePropertyChanged("_message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _no {
            get {
                return this._noField;
            }
            set {
                if ((this._noField.Equals(value) != true)) {
                    this._noField = value;
                    this.RaisePropertyChanged("_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _order_no {
            get {
                return this._order_noField;
            }
            set {
                if ((this._order_noField.Equals(value) != true)) {
                    this._order_noField = value;
                    this.RaisePropertyChanged("_order_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _price_fraction_proc_id {
            get {
                return this._price_fraction_proc_idField;
            }
            set {
                if ((this._price_fraction_proc_idField.Equals(value) != true)) {
                    this._price_fraction_proc_idField = value;
                    this.RaisePropertyChanged("_price_fraction_proc_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _profits_percent {
            get {
                return this._profits_percentField;
            }
            set {
                if ((this._profits_percentField.Equals(value) != true)) {
                    this._profits_percentField = value;
                    this.RaisePropertyChanged("_profits_percent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _receipt_receivable_kbn {
            get {
                return this._receipt_receivable_kbnField;
            }
            set {
                if ((this._receipt_receivable_kbnField.Equals(value) != true)) {
                    this._receipt_receivable_kbnField = value;
                    this.RaisePropertyChanged("_receipt_receivable_kbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _receipt_receivable_kbn_nm {
            get {
                return this._receipt_receivable_kbn_nmField;
            }
            set {
                if ((object.ReferenceEquals(this._receipt_receivable_kbn_nmField, value) != true)) {
                    this._receipt_receivable_kbn_nmField = value;
                    this.RaisePropertyChanged("_receipt_receivable_kbn_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _red_before_no {
            get {
                return this._red_before_noField;
            }
            set {
                if ((this._red_before_noField.Equals(value) != true)) {
                    this._red_before_noField = value;
                    this.RaisePropertyChanged("_red_before_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sales_credit_price {
            get {
                return this._sales_credit_priceField;
            }
            set {
                if ((this._sales_credit_priceField.Equals(value) != true)) {
                    this._sales_credit_priceField = value;
                    this.RaisePropertyChanged("_sales_credit_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _sales_ymd {
            get {
                return this._sales_ymdField;
            }
            set {
                if ((object.ReferenceEquals(this._sales_ymdField, value) != true)) {
                    this._sales_ymdField = value;
                    this.RaisePropertyChanged("_sales_ymd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sum_case_number {
            get {
                return this._sum_case_numberField;
            }
            set {
                if ((this._sum_case_numberField.Equals(value) != true)) {
                    this._sum_case_numberField = value;
                    this.RaisePropertyChanged("_sum_case_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sum_enter_number {
            get {
                return this._sum_enter_numberField;
            }
            set {
                if ((this._sum_enter_numberField.Equals(value) != true)) {
                    this._sum_enter_numberField = value;
                    this.RaisePropertyChanged("_sum_enter_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sum_no_tax_price {
            get {
                return this._sum_no_tax_priceField;
            }
            set {
                if ((this._sum_no_tax_priceField.Equals(value) != true)) {
                    this._sum_no_tax_priceField = value;
                    this.RaisePropertyChanged("_sum_no_tax_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sum_number {
            get {
                return this._sum_numberField;
            }
            set {
                if ((this._sum_numberField.Equals(value) != true)) {
                    this._sum_numberField = value;
                    this.RaisePropertyChanged("_sum_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sum_price {
            get {
                return this._sum_priceField;
            }
            set {
                if ((this._sum_priceField.Equals(value) != true)) {
                    this._sum_priceField = value;
                    this.RaisePropertyChanged("_sum_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sum_profits {
            get {
                return this._sum_profitsField;
            }
            set {
                if ((this._sum_profitsField.Equals(value) != true)) {
                    this._sum_profitsField = value;
                    this.RaisePropertyChanged("_sum_profits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sum_sales_cost {
            get {
                return this._sum_sales_costField;
            }
            set {
                if ((this._sum_sales_costField.Equals(value) != true)) {
                    this._sum_sales_costField = value;
                    this.RaisePropertyChanged("_sum_sales_cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sum_tax {
            get {
                return this._sum_taxField;
            }
            set {
                if ((this._sum_taxField.Equals(value) != true)) {
                    this._sum_taxField = value;
                    this.RaisePropertyChanged("_sum_tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sum_unit_price {
            get {
                return this._sum_unit_priceField;
            }
            set {
                if ((this._sum_unit_priceField.Equals(value) != true)) {
                    this._sum_unit_priceField = value;
                    this.RaisePropertyChanged("_sum_unit_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _supplier_id {
            get {
                return this._supplier_idField;
            }
            set {
                if ((object.ReferenceEquals(this._supplier_idField, value) != true)) {
                    this._supplier_idField = value;
                    this.RaisePropertyChanged("_supplier_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _supplier_name {
            get {
                return this._supplier_nameField;
            }
            set {
                if ((object.ReferenceEquals(this._supplier_nameField, value) != true)) {
                    this._supplier_nameField = value;
                    this.RaisePropertyChanged("_supplier_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _supply_ymd {
            get {
                return this._supply_ymdField;
            }
            set {
                if ((object.ReferenceEquals(this._supply_ymdField, value) != true)) {
                    this._supply_ymdField = value;
                    this.RaisePropertyChanged("_supply_ymd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _tax_change_id {
            get {
                return this._tax_change_idField;
            }
            set {
                if ((this._tax_change_idField.Equals(value) != true)) {
                    this._tax_change_idField = value;
                    this.RaisePropertyChanged("_tax_change_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _tax_change_name {
            get {
                return this._tax_change_nameField;
            }
            set {
                if ((object.ReferenceEquals(this._tax_change_nameField, value) != true)) {
                    this._tax_change_nameField = value;
                    this.RaisePropertyChanged("_tax_change_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _tax_fraction_proc_id {
            get {
                return this._tax_fraction_proc_idField;
            }
            set {
                if ((this._tax_fraction_proc_idField.Equals(value) != true)) {
                    this._tax_fraction_proc_idField = value;
                    this.RaisePropertyChanged("_tax_fraction_proc_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _unit_kind_id {
            get {
                return this._unit_kind_idField;
            }
            set {
                if ((this._unit_kind_idField.Equals(value) != true)) {
                    this._unit_kind_idField = value;
                    this.RaisePropertyChanged("_unit_kind_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _update_date {
            get {
                return this._update_dateField;
            }
            set {
                if ((object.ReferenceEquals(this._update_dateField, value) != true)) {
                    this._update_dateField = value;
                    this.RaisePropertyChanged("_update_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _update_flg {
            get {
                return this._update_flgField;
            }
            set {
                if ((this._update_flgField.Equals(value) != true)) {
                    this._update_flgField = value;
                    this.RaisePropertyChanged("_update_flg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _update_person_id {
            get {
                return this._update_person_idField;
            }
            set {
                if ((this._update_person_idField.Equals(value) != true)) {
                    this._update_person_idField = value;
                    this.RaisePropertyChanged("_update_person_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _update_person_nm {
            get {
                return this._update_person_nmField;
            }
            set {
                if ((object.ReferenceEquals(this._update_person_nmField, value) != true)) {
                    this._update_person_nmField = value;
                    this.RaisePropertyChanged("_update_person_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _update_time {
            get {
                return this._update_timeField;
            }
            set {
                if ((this._update_timeField.Equals(value) != true)) {
                    this._update_timeField = value;
                    this.RaisePropertyChanged("_update_time");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="svcSales.svcSales")]
    public interface svcSales {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:svcSales/GetSalesH", ReplyAction="urn:svcSales/GetSalesHResponse")]
        System.IAsyncResult BeginGetSalesH(string random, long SalesIDFrom, long SalesIDTo, System.AsyncCallback callback, object asyncState);
        
        SlvHanbaiClient.svcSales.EntitySalesH EndGetSalesH(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:svcSales/GetSalesListD", ReplyAction="urn:svcSales/GetSalesListDResponse")]
        System.IAsyncResult BeginGetSalesListD(string random, long SalesIDFrom, long SalesIDTo, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> EndGetSalesListD(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:svcSales/GetSalesList", ReplyAction="urn:svcSales/GetSalesListResponse")]
        System.IAsyncResult BeginGetSalesList(string random, string strWhereSql, string strSalesBySql, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySales> EndGetSalesList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:svcSales/UpdateSales", ReplyAction="urn:svcSales/UpdateSalesResponse")]
        System.IAsyncResult BeginUpdateSales(string random, int type, long SalesNo, SlvHanbaiClient.svcSales.EntitySalesH entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> entityD, SlvHanbaiClient.svcSales.EntitySalesH before_entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> before_entityD, System.AsyncCallback callback, object asyncState);
        
        string EndUpdateSales(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:svcSales/UpdateSalesPrint", ReplyAction="urn:svcSales/UpdateSalesPrintResponse")]
        System.IAsyncResult BeginUpdateSalesPrint(string random, int type, string _no, System.AsyncCallback callback, object asyncState);
        
        void EndUpdateSalesPrint(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface svcSalesChannel : SlvHanbaiClient.svcSales.svcSales, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSalesHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSalesHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SlvHanbaiClient.svcSales.EntitySalesH Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SlvHanbaiClient.svcSales.EntitySalesH)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSalesListDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSalesListDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSalesListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSalesListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySales> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySales>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateSalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateSalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class svcSalesClient : System.ServiceModel.ClientBase<SlvHanbaiClient.svcSales.svcSales>, SlvHanbaiClient.svcSales.svcSales {
        
        private BeginOperationDelegate onBeginGetSalesHDelegate;
        
        private EndOperationDelegate onEndGetSalesHDelegate;
        
        private System.Threading.SendOrPostCallback onGetSalesHCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSalesListDDelegate;
        
        private EndOperationDelegate onEndGetSalesListDDelegate;
        
        private System.Threading.SendOrPostCallback onGetSalesListDCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSalesListDelegate;
        
        private EndOperationDelegate onEndGetSalesListDelegate;
        
        private System.Threading.SendOrPostCallback onGetSalesListCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateSalesDelegate;
        
        private EndOperationDelegate onEndUpdateSalesDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateSalesCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateSalesPrintDelegate;
        
        private EndOperationDelegate onEndUpdateSalesPrintDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateSalesPrintCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public svcSalesClient() {
        }
        
        public svcSalesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public svcSalesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcSalesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcSalesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("CookieContainer を設定できません。バインドに HttpCookieContainerBindingElement が含まれていることを確認してくだ" +
                            "さい。");
                }
            }
        }
        
        public event System.EventHandler<GetSalesHCompletedEventArgs> GetSalesHCompleted;
        
        public event System.EventHandler<GetSalesListDCompletedEventArgs> GetSalesListDCompleted;
        
        public event System.EventHandler<GetSalesListCompletedEventArgs> GetSalesListCompleted;
        
        public event System.EventHandler<UpdateSalesCompletedEventArgs> UpdateSalesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdateSalesPrintCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SlvHanbaiClient.svcSales.svcSales.BeginGetSalesH(string random, long SalesIDFrom, long SalesIDTo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSalesH(random, SalesIDFrom, SalesIDTo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SlvHanbaiClient.svcSales.EntitySalesH SlvHanbaiClient.svcSales.svcSales.EndGetSalesH(System.IAsyncResult result) {
            return base.Channel.EndGetSalesH(result);
        }
        
        private System.IAsyncResult OnBeginGetSalesH(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string random = ((string)(inValues[0]));
            long SalesIDFrom = ((long)(inValues[1]));
            long SalesIDTo = ((long)(inValues[2]));
            return ((SlvHanbaiClient.svcSales.svcSales)(this)).BeginGetSalesH(random, SalesIDFrom, SalesIDTo, callback, asyncState);
        }
        
        private object[] OnEndGetSalesH(System.IAsyncResult result) {
            SlvHanbaiClient.svcSales.EntitySalesH retVal = ((SlvHanbaiClient.svcSales.svcSales)(this)).EndGetSalesH(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSalesHCompleted(object state) {
            if ((this.GetSalesHCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSalesHCompleted(this, new GetSalesHCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSalesHAsync(string random, long SalesIDFrom, long SalesIDTo) {
            this.GetSalesHAsync(random, SalesIDFrom, SalesIDTo, null);
        }
        
        public void GetSalesHAsync(string random, long SalesIDFrom, long SalesIDTo, object userState) {
            if ((this.onBeginGetSalesHDelegate == null)) {
                this.onBeginGetSalesHDelegate = new BeginOperationDelegate(this.OnBeginGetSalesH);
            }
            if ((this.onEndGetSalesHDelegate == null)) {
                this.onEndGetSalesHDelegate = new EndOperationDelegate(this.OnEndGetSalesH);
            }
            if ((this.onGetSalesHCompletedDelegate == null)) {
                this.onGetSalesHCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSalesHCompleted);
            }
            base.InvokeAsync(this.onBeginGetSalesHDelegate, new object[] {
                        random,
                        SalesIDFrom,
                        SalesIDTo}, this.onEndGetSalesHDelegate, this.onGetSalesHCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SlvHanbaiClient.svcSales.svcSales.BeginGetSalesListD(string random, long SalesIDFrom, long SalesIDTo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSalesListD(random, SalesIDFrom, SalesIDTo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> SlvHanbaiClient.svcSales.svcSales.EndGetSalesListD(System.IAsyncResult result) {
            return base.Channel.EndGetSalesListD(result);
        }
        
        private System.IAsyncResult OnBeginGetSalesListD(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string random = ((string)(inValues[0]));
            long SalesIDFrom = ((long)(inValues[1]));
            long SalesIDTo = ((long)(inValues[2]));
            return ((SlvHanbaiClient.svcSales.svcSales)(this)).BeginGetSalesListD(random, SalesIDFrom, SalesIDTo, callback, asyncState);
        }
        
        private object[] OnEndGetSalesListD(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> retVal = ((SlvHanbaiClient.svcSales.svcSales)(this)).EndGetSalesListD(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSalesListDCompleted(object state) {
            if ((this.GetSalesListDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSalesListDCompleted(this, new GetSalesListDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSalesListDAsync(string random, long SalesIDFrom, long SalesIDTo) {
            this.GetSalesListDAsync(random, SalesIDFrom, SalesIDTo, null);
        }
        
        public void GetSalesListDAsync(string random, long SalesIDFrom, long SalesIDTo, object userState) {
            if ((this.onBeginGetSalesListDDelegate == null)) {
                this.onBeginGetSalesListDDelegate = new BeginOperationDelegate(this.OnBeginGetSalesListD);
            }
            if ((this.onEndGetSalesListDDelegate == null)) {
                this.onEndGetSalesListDDelegate = new EndOperationDelegate(this.OnEndGetSalesListD);
            }
            if ((this.onGetSalesListDCompletedDelegate == null)) {
                this.onGetSalesListDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSalesListDCompleted);
            }
            base.InvokeAsync(this.onBeginGetSalesListDDelegate, new object[] {
                        random,
                        SalesIDFrom,
                        SalesIDTo}, this.onEndGetSalesListDDelegate, this.onGetSalesListDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SlvHanbaiClient.svcSales.svcSales.BeginGetSalesList(string random, string strWhereSql, string strSalesBySql, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSalesList(random, strWhereSql, strSalesBySql, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySales> SlvHanbaiClient.svcSales.svcSales.EndGetSalesList(System.IAsyncResult result) {
            return base.Channel.EndGetSalesList(result);
        }
        
        private System.IAsyncResult OnBeginGetSalesList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string random = ((string)(inValues[0]));
            string strWhereSql = ((string)(inValues[1]));
            string strSalesBySql = ((string)(inValues[2]));
            return ((SlvHanbaiClient.svcSales.svcSales)(this)).BeginGetSalesList(random, strWhereSql, strSalesBySql, callback, asyncState);
        }
        
        private object[] OnEndGetSalesList(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySales> retVal = ((SlvHanbaiClient.svcSales.svcSales)(this)).EndGetSalesList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSalesListCompleted(object state) {
            if ((this.GetSalesListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSalesListCompleted(this, new GetSalesListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSalesListAsync(string random, string strWhereSql, string strSalesBySql) {
            this.GetSalesListAsync(random, strWhereSql, strSalesBySql, null);
        }
        
        public void GetSalesListAsync(string random, string strWhereSql, string strSalesBySql, object userState) {
            if ((this.onBeginGetSalesListDelegate == null)) {
                this.onBeginGetSalesListDelegate = new BeginOperationDelegate(this.OnBeginGetSalesList);
            }
            if ((this.onEndGetSalesListDelegate == null)) {
                this.onEndGetSalesListDelegate = new EndOperationDelegate(this.OnEndGetSalesList);
            }
            if ((this.onGetSalesListCompletedDelegate == null)) {
                this.onGetSalesListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSalesListCompleted);
            }
            base.InvokeAsync(this.onBeginGetSalesListDelegate, new object[] {
                        random,
                        strWhereSql,
                        strSalesBySql}, this.onEndGetSalesListDelegate, this.onGetSalesListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SlvHanbaiClient.svcSales.svcSales.BeginUpdateSales(string random, int type, long SalesNo, SlvHanbaiClient.svcSales.EntitySalesH entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> entityD, SlvHanbaiClient.svcSales.EntitySalesH before_entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> before_entityD, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateSales(random, type, SalesNo, entityH, entityD, before_entityH, before_entityD, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string SlvHanbaiClient.svcSales.svcSales.EndUpdateSales(System.IAsyncResult result) {
            return base.Channel.EndUpdateSales(result);
        }
        
        private System.IAsyncResult OnBeginUpdateSales(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string random = ((string)(inValues[0]));
            int type = ((int)(inValues[1]));
            long SalesNo = ((long)(inValues[2]));
            SlvHanbaiClient.svcSales.EntitySalesH entityH = ((SlvHanbaiClient.svcSales.EntitySalesH)(inValues[3]));
            System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> entityD = ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD>)(inValues[4]));
            SlvHanbaiClient.svcSales.EntitySalesH before_entityH = ((SlvHanbaiClient.svcSales.EntitySalesH)(inValues[5]));
            System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> before_entityD = ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD>)(inValues[6]));
            return ((SlvHanbaiClient.svcSales.svcSales)(this)).BeginUpdateSales(random, type, SalesNo, entityH, entityD, before_entityH, before_entityD, callback, asyncState);
        }
        
        private object[] OnEndUpdateSales(System.IAsyncResult result) {
            string retVal = ((SlvHanbaiClient.svcSales.svcSales)(this)).EndUpdateSales(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateSalesCompleted(object state) {
            if ((this.UpdateSalesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateSalesCompleted(this, new UpdateSalesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateSalesAsync(string random, int type, long SalesNo, SlvHanbaiClient.svcSales.EntitySalesH entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> entityD, SlvHanbaiClient.svcSales.EntitySalesH before_entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> before_entityD) {
            this.UpdateSalesAsync(random, type, SalesNo, entityH, entityD, before_entityH, before_entityD, null);
        }
        
        public void UpdateSalesAsync(string random, int type, long SalesNo, SlvHanbaiClient.svcSales.EntitySalesH entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> entityD, SlvHanbaiClient.svcSales.EntitySalesH before_entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> before_entityD, object userState) {
            if ((this.onBeginUpdateSalesDelegate == null)) {
                this.onBeginUpdateSalesDelegate = new BeginOperationDelegate(this.OnBeginUpdateSales);
            }
            if ((this.onEndUpdateSalesDelegate == null)) {
                this.onEndUpdateSalesDelegate = new EndOperationDelegate(this.OnEndUpdateSales);
            }
            if ((this.onUpdateSalesCompletedDelegate == null)) {
                this.onUpdateSalesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateSalesCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateSalesDelegate, new object[] {
                        random,
                        type,
                        SalesNo,
                        entityH,
                        entityD,
                        before_entityH,
                        before_entityD}, this.onEndUpdateSalesDelegate, this.onUpdateSalesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SlvHanbaiClient.svcSales.svcSales.BeginUpdateSalesPrint(string random, int type, string _no, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateSalesPrint(random, type, _no, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SlvHanbaiClient.svcSales.svcSales.EndUpdateSalesPrint(System.IAsyncResult result) {
            base.Channel.EndUpdateSalesPrint(result);
        }
        
        private System.IAsyncResult OnBeginUpdateSalesPrint(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string random = ((string)(inValues[0]));
            int type = ((int)(inValues[1]));
            string _no = ((string)(inValues[2]));
            return ((SlvHanbaiClient.svcSales.svcSales)(this)).BeginUpdateSalesPrint(random, type, _no, callback, asyncState);
        }
        
        private object[] OnEndUpdateSalesPrint(System.IAsyncResult result) {
            ((SlvHanbaiClient.svcSales.svcSales)(this)).EndUpdateSalesPrint(result);
            return null;
        }
        
        private void OnUpdateSalesPrintCompleted(object state) {
            if ((this.UpdateSalesPrintCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateSalesPrintCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateSalesPrintAsync(string random, int type, string _no) {
            this.UpdateSalesPrintAsync(random, type, _no, null);
        }
        
        public void UpdateSalesPrintAsync(string random, int type, string _no, object userState) {
            if ((this.onBeginUpdateSalesPrintDelegate == null)) {
                this.onBeginUpdateSalesPrintDelegate = new BeginOperationDelegate(this.OnBeginUpdateSalesPrint);
            }
            if ((this.onEndUpdateSalesPrintDelegate == null)) {
                this.onEndUpdateSalesPrintDelegate = new EndOperationDelegate(this.OnEndUpdateSalesPrint);
            }
            if ((this.onUpdateSalesPrintCompletedDelegate == null)) {
                this.onUpdateSalesPrintCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateSalesPrintCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateSalesPrintDelegate, new object[] {
                        random,
                        type,
                        _no}, this.onEndUpdateSalesPrintDelegate, this.onUpdateSalesPrintCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SlvHanbaiClient.svcSales.svcSales CreateChannel() {
            return new svcSalesClientChannel(this);
        }
        
        private class svcSalesClientChannel : ChannelBase<SlvHanbaiClient.svcSales.svcSales>, SlvHanbaiClient.svcSales.svcSales {
            
            public svcSalesClientChannel(System.ServiceModel.ClientBase<SlvHanbaiClient.svcSales.svcSales> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetSalesH(string random, long SalesIDFrom, long SalesIDTo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = random;
                _args[1] = SalesIDFrom;
                _args[2] = SalesIDTo;
                System.IAsyncResult _result = base.BeginInvoke("GetSalesH", _args, callback, asyncState);
                return _result;
            }
            
            public SlvHanbaiClient.svcSales.EntitySalesH EndGetSalesH(System.IAsyncResult result) {
                object[] _args = new object[0];
                SlvHanbaiClient.svcSales.EntitySalesH _result = ((SlvHanbaiClient.svcSales.EntitySalesH)(base.EndInvoke("GetSalesH", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSalesListD(string random, long SalesIDFrom, long SalesIDTo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = random;
                _args[1] = SalesIDFrom;
                _args[2] = SalesIDTo;
                System.IAsyncResult _result = base.BeginInvoke("GetSalesListD", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> EndGetSalesListD(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> _result = ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD>)(base.EndInvoke("GetSalesListD", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSalesList(string random, string strWhereSql, string strSalesBySql, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = random;
                _args[1] = strWhereSql;
                _args[2] = strSalesBySql;
                System.IAsyncResult _result = base.BeginInvoke("GetSalesList", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySales> EndGetSalesList(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySales> _result = ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySales>)(base.EndInvoke("GetSalesList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateSales(string random, int type, long SalesNo, SlvHanbaiClient.svcSales.EntitySalesH entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> entityD, SlvHanbaiClient.svcSales.EntitySalesH before_entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcSales.EntitySalesD> before_entityD, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[7];
                _args[0] = random;
                _args[1] = type;
                _args[2] = SalesNo;
                _args[3] = entityH;
                _args[4] = entityD;
                _args[5] = before_entityH;
                _args[6] = before_entityD;
                System.IAsyncResult _result = base.BeginInvoke("UpdateSales", _args, callback, asyncState);
                return _result;
            }
            
            public string EndUpdateSales(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("UpdateSales", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateSalesPrint(string random, int type, string _no, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = random;
                _args[1] = type;
                _args[2] = _no;
                System.IAsyncResult _result = base.BeginInvoke("UpdateSalesPrint", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUpdateSalesPrint(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("UpdateSalesPrint", _args, result);
            }
        }
    }
}
