//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.237
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace SlvHanbaiClient.svcPaymentCash {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/SlvHanbai.Web.Class.Entity")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SlvHanbaiClient.svcPaymentCash.EntityPaymentCash))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH))]
    public partial class EntityBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPaymentCashD", Namespace="http://schemas.datacontract.org/2004/07/SlvHanbai.Web.Class.Entity")]
    public partial class EntityPaymentCashD : SlvHanbaiClient.svcPaymentCash.EntityBase {
        
        private string _bill_site_dayField;
        
        private long _idField;
        
        private int _lock_flgField;
        
        private string _memoField;
        
        private string _messageField;
        
        private string _payment_cash_division_idField;
        
        private string _payment_cash_division_nmField;
        
        private double _priceField;
        
        private int _rec_noField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _bill_site_day {
            get {
                return this._bill_site_dayField;
            }
            set {
                if ((object.ReferenceEquals(this._bill_site_dayField, value) != true)) {
                    this._bill_site_dayField = value;
                    this.RaisePropertyChanged("_bill_site_day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _lock_flg {
            get {
                return this._lock_flgField;
            }
            set {
                if ((this._lock_flgField.Equals(value) != true)) {
                    this._lock_flgField = value;
                    this.RaisePropertyChanged("_lock_flg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _memo {
            get {
                return this._memoField;
            }
            set {
                if ((object.ReferenceEquals(this._memoField, value) != true)) {
                    this._memoField = value;
                    this.RaisePropertyChanged("_memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _message {
            get {
                return this._messageField;
            }
            set {
                if ((object.ReferenceEquals(this._messageField, value) != true)) {
                    this._messageField = value;
                    this.RaisePropertyChanged("_message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _payment_cash_division_id {
            get {
                return this._payment_cash_division_idField;
            }
            set {
                if ((object.ReferenceEquals(this._payment_cash_division_idField, value) != true)) {
                    this._payment_cash_division_idField = value;
                    this.RaisePropertyChanged("_payment_cash_division_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _payment_cash_division_nm {
            get {
                return this._payment_cash_division_nmField;
            }
            set {
                if ((object.ReferenceEquals(this._payment_cash_division_nmField, value) != true)) {
                    this._payment_cash_division_nmField = value;
                    this.RaisePropertyChanged("_payment_cash_division_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _price {
            get {
                return this._priceField;
            }
            set {
                if ((this._priceField.Equals(value) != true)) {
                    this._priceField = value;
                    this.RaisePropertyChanged("_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _rec_no {
            get {
                return this._rec_noField;
            }
            set {
                if ((this._rec_noField.Equals(value) != true)) {
                    this._rec_noField = value;
                    this.RaisePropertyChanged("_rec_no");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPaymentCash", Namespace="http://schemas.datacontract.org/2004/07/SlvHanbai.Web.Class.Entity")]
    public partial class EntityPaymentCash : SlvHanbaiClient.svcPaymentCash.EntityBase {
        
        private string bill_site_dayField;
        
        private string d_memoField;
        
        private long idField;
        
        private int input_personField;
        
        private string input_person_nmField;
        
        private string memoField;
        
        private string messageField;
        
        private long noField;
        
        private int payment_cash_division_idField;
        
        private string payment_cash_division_nmField;
        
        private string payment_cash_ymdField;
        
        private double priceField;
        
        private string purchase_idField;
        
        private string purchase_nmField;
        
        private int rec_noField;
        
        private double sum_priceField;
        
        private int update_person_idField;
        
        private string update_person_nmField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bill_site_day {
            get {
                return this.bill_site_dayField;
            }
            set {
                if ((object.ReferenceEquals(this.bill_site_dayField, value) != true)) {
                    this.bill_site_dayField = value;
                    this.RaisePropertyChanged("bill_site_day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string d_memo {
            get {
                return this.d_memoField;
            }
            set {
                if ((object.ReferenceEquals(this.d_memoField, value) != true)) {
                    this.d_memoField = value;
                    this.RaisePropertyChanged("d_memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int input_person {
            get {
                return this.input_personField;
            }
            set {
                if ((this.input_personField.Equals(value) != true)) {
                    this.input_personField = value;
                    this.RaisePropertyChanged("input_person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string input_person_nm {
            get {
                return this.input_person_nmField;
            }
            set {
                if ((object.ReferenceEquals(this.input_person_nmField, value) != true)) {
                    this.input_person_nmField = value;
                    this.RaisePropertyChanged("input_person_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string memo {
            get {
                return this.memoField;
            }
            set {
                if ((object.ReferenceEquals(this.memoField, value) != true)) {
                    this.memoField = value;
                    this.RaisePropertyChanged("memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long no {
            get {
                return this.noField;
            }
            set {
                if ((this.noField.Equals(value) != true)) {
                    this.noField = value;
                    this.RaisePropertyChanged("no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int payment_cash_division_id {
            get {
                return this.payment_cash_division_idField;
            }
            set {
                if ((this.payment_cash_division_idField.Equals(value) != true)) {
                    this.payment_cash_division_idField = value;
                    this.RaisePropertyChanged("payment_cash_division_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payment_cash_division_nm {
            get {
                return this.payment_cash_division_nmField;
            }
            set {
                if ((object.ReferenceEquals(this.payment_cash_division_nmField, value) != true)) {
                    this.payment_cash_division_nmField = value;
                    this.RaisePropertyChanged("payment_cash_division_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payment_cash_ymd {
            get {
                return this.payment_cash_ymdField;
            }
            set {
                if ((object.ReferenceEquals(this.payment_cash_ymdField, value) != true)) {
                    this.payment_cash_ymdField = value;
                    this.RaisePropertyChanged("payment_cash_ymd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string purchase_id {
            get {
                return this.purchase_idField;
            }
            set {
                if ((object.ReferenceEquals(this.purchase_idField, value) != true)) {
                    this.purchase_idField = value;
                    this.RaisePropertyChanged("purchase_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string purchase_nm {
            get {
                return this.purchase_nmField;
            }
            set {
                if ((object.ReferenceEquals(this.purchase_nmField, value) != true)) {
                    this.purchase_nmField = value;
                    this.RaisePropertyChanged("purchase_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rec_no {
            get {
                return this.rec_noField;
            }
            set {
                if ((this.rec_noField.Equals(value) != true)) {
                    this.rec_noField = value;
                    this.RaisePropertyChanged("rec_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double sum_price {
            get {
                return this.sum_priceField;
            }
            set {
                if ((this.sum_priceField.Equals(value) != true)) {
                    this.sum_priceField = value;
                    this.RaisePropertyChanged("sum_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int update_person_id {
            get {
                return this.update_person_idField;
            }
            set {
                if ((this.update_person_idField.Equals(value) != true)) {
                    this.update_person_idField = value;
                    this.RaisePropertyChanged("update_person_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string update_person_nm {
            get {
                return this.update_person_nmField;
            }
            set {
                if ((object.ReferenceEquals(this.update_person_nmField, value) != true)) {
                    this.update_person_nmField = value;
                    this.RaisePropertyChanged("update_person_nm");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPaymentCashH", Namespace="http://schemas.datacontract.org/2004/07/SlvHanbai.Web.Class.Entity")]
    public partial class EntityPaymentCashH : SlvHanbaiClient.svcPaymentCash.EntityBase {
        
        private double _before_credit_priceField;
        
        private double _before_payment_cash_priceField;
        
        private double _credit_priceField;
        
        private long _idField;
        
        private int _lock_flgField;
        
        private string _memoField;
        
        private string _messageField;
        
        private long _noField;
        
        private string _payment_cash_ymdField;
        
        private int _payment_close_flgField;
        
        private string _payment_division_idField;
        
        private string _payment_division_nmField;
        
        private int _payment_kbnField;
        
        private string _payment_kbn_nmField;
        
        private long _payment_noField;
        
        private string _payment_plan_dayField;
        
        private double _payment_priceField;
        
        private string _payment_yyyymmddField;
        
        private int _person_idField;
        
        private string _person_nameField;
        
        private string _purchase_idField;
        
        private string _purchase_nameField;
        
        private double _sum_priceField;
        
        private int _summing_up_dayField;
        
        private string _summing_up_group_idField;
        
        private string _summing_up_group_nmField;
        
        private string _update_dateField;
        
        private int _update_flgField;
        
        private int _update_person_idField;
        
        private string _update_person_nmField;
        
        private System.DateTime _update_timeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _before_credit_price {
            get {
                return this._before_credit_priceField;
            }
            set {
                if ((this._before_credit_priceField.Equals(value) != true)) {
                    this._before_credit_priceField = value;
                    this.RaisePropertyChanged("_before_credit_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _before_payment_cash_price {
            get {
                return this._before_payment_cash_priceField;
            }
            set {
                if ((this._before_payment_cash_priceField.Equals(value) != true)) {
                    this._before_payment_cash_priceField = value;
                    this.RaisePropertyChanged("_before_payment_cash_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _credit_price {
            get {
                return this._credit_priceField;
            }
            set {
                if ((this._credit_priceField.Equals(value) != true)) {
                    this._credit_priceField = value;
                    this.RaisePropertyChanged("_credit_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _lock_flg {
            get {
                return this._lock_flgField;
            }
            set {
                if ((this._lock_flgField.Equals(value) != true)) {
                    this._lock_flgField = value;
                    this.RaisePropertyChanged("_lock_flg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _memo {
            get {
                return this._memoField;
            }
            set {
                if ((object.ReferenceEquals(this._memoField, value) != true)) {
                    this._memoField = value;
                    this.RaisePropertyChanged("_memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _message {
            get {
                return this._messageField;
            }
            set {
                if ((object.ReferenceEquals(this._messageField, value) != true)) {
                    this._messageField = value;
                    this.RaisePropertyChanged("_message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _no {
            get {
                return this._noField;
            }
            set {
                if ((this._noField.Equals(value) != true)) {
                    this._noField = value;
                    this.RaisePropertyChanged("_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _payment_cash_ymd {
            get {
                return this._payment_cash_ymdField;
            }
            set {
                if ((object.ReferenceEquals(this._payment_cash_ymdField, value) != true)) {
                    this._payment_cash_ymdField = value;
                    this.RaisePropertyChanged("_payment_cash_ymd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _payment_close_flg {
            get {
                return this._payment_close_flgField;
            }
            set {
                if ((this._payment_close_flgField.Equals(value) != true)) {
                    this._payment_close_flgField = value;
                    this.RaisePropertyChanged("_payment_close_flg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _payment_division_id {
            get {
                return this._payment_division_idField;
            }
            set {
                if ((object.ReferenceEquals(this._payment_division_idField, value) != true)) {
                    this._payment_division_idField = value;
                    this.RaisePropertyChanged("_payment_division_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _payment_division_nm {
            get {
                return this._payment_division_nmField;
            }
            set {
                if ((object.ReferenceEquals(this._payment_division_nmField, value) != true)) {
                    this._payment_division_nmField = value;
                    this.RaisePropertyChanged("_payment_division_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _payment_kbn {
            get {
                return this._payment_kbnField;
            }
            set {
                if ((this._payment_kbnField.Equals(value) != true)) {
                    this._payment_kbnField = value;
                    this.RaisePropertyChanged("_payment_kbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _payment_kbn_nm {
            get {
                return this._payment_kbn_nmField;
            }
            set {
                if ((object.ReferenceEquals(this._payment_kbn_nmField, value) != true)) {
                    this._payment_kbn_nmField = value;
                    this.RaisePropertyChanged("_payment_kbn_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _payment_no {
            get {
                return this._payment_noField;
            }
            set {
                if ((this._payment_noField.Equals(value) != true)) {
                    this._payment_noField = value;
                    this.RaisePropertyChanged("_payment_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _payment_plan_day {
            get {
                return this._payment_plan_dayField;
            }
            set {
                if ((object.ReferenceEquals(this._payment_plan_dayField, value) != true)) {
                    this._payment_plan_dayField = value;
                    this.RaisePropertyChanged("_payment_plan_day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _payment_price {
            get {
                return this._payment_priceField;
            }
            set {
                if ((this._payment_priceField.Equals(value) != true)) {
                    this._payment_priceField = value;
                    this.RaisePropertyChanged("_payment_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _payment_yyyymmdd {
            get {
                return this._payment_yyyymmddField;
            }
            set {
                if ((object.ReferenceEquals(this._payment_yyyymmddField, value) != true)) {
                    this._payment_yyyymmddField = value;
                    this.RaisePropertyChanged("_payment_yyyymmdd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _person_id {
            get {
                return this._person_idField;
            }
            set {
                if ((this._person_idField.Equals(value) != true)) {
                    this._person_idField = value;
                    this.RaisePropertyChanged("_person_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _person_name {
            get {
                return this._person_nameField;
            }
            set {
                if ((object.ReferenceEquals(this._person_nameField, value) != true)) {
                    this._person_nameField = value;
                    this.RaisePropertyChanged("_person_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _purchase_id {
            get {
                return this._purchase_idField;
            }
            set {
                if ((object.ReferenceEquals(this._purchase_idField, value) != true)) {
                    this._purchase_idField = value;
                    this.RaisePropertyChanged("_purchase_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _purchase_name {
            get {
                return this._purchase_nameField;
            }
            set {
                if ((object.ReferenceEquals(this._purchase_nameField, value) != true)) {
                    this._purchase_nameField = value;
                    this.RaisePropertyChanged("_purchase_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double _sum_price {
            get {
                return this._sum_priceField;
            }
            set {
                if ((this._sum_priceField.Equals(value) != true)) {
                    this._sum_priceField = value;
                    this.RaisePropertyChanged("_sum_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _summing_up_day {
            get {
                return this._summing_up_dayField;
            }
            set {
                if ((this._summing_up_dayField.Equals(value) != true)) {
                    this._summing_up_dayField = value;
                    this.RaisePropertyChanged("_summing_up_day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _summing_up_group_id {
            get {
                return this._summing_up_group_idField;
            }
            set {
                if ((object.ReferenceEquals(this._summing_up_group_idField, value) != true)) {
                    this._summing_up_group_idField = value;
                    this.RaisePropertyChanged("_summing_up_group_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _summing_up_group_nm {
            get {
                return this._summing_up_group_nmField;
            }
            set {
                if ((object.ReferenceEquals(this._summing_up_group_nmField, value) != true)) {
                    this._summing_up_group_nmField = value;
                    this.RaisePropertyChanged("_summing_up_group_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _update_date {
            get {
                return this._update_dateField;
            }
            set {
                if ((object.ReferenceEquals(this._update_dateField, value) != true)) {
                    this._update_dateField = value;
                    this.RaisePropertyChanged("_update_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _update_flg {
            get {
                return this._update_flgField;
            }
            set {
                if ((this._update_flgField.Equals(value) != true)) {
                    this._update_flgField = value;
                    this.RaisePropertyChanged("_update_flg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _update_person_id {
            get {
                return this._update_person_idField;
            }
            set {
                if ((this._update_person_idField.Equals(value) != true)) {
                    this._update_person_idField = value;
                    this.RaisePropertyChanged("_update_person_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _update_person_nm {
            get {
                return this._update_person_nmField;
            }
            set {
                if ((object.ReferenceEquals(this._update_person_nmField, value) != true)) {
                    this._update_person_nmField = value;
                    this.RaisePropertyChanged("_update_person_nm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _update_time {
            get {
                return this._update_timeField;
            }
            set {
                if ((this._update_timeField.Equals(value) != true)) {
                    this._update_timeField = value;
                    this.RaisePropertyChanged("_update_time");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="svcPaymentCash.svcPaymentCash")]
    public interface svcPaymentCash {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:svcPaymentCash/GetPaymentCashH", ReplyAction="urn:svcPaymentCash/GetPaymentCashHResponse")]
        System.IAsyncResult BeginGetPaymentCashH(string random, long payment_cash_no, System.AsyncCallback callback, object asyncState);
        
        SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH EndGetPaymentCashH(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:svcPaymentCash/GetPaymentCashD", ReplyAction="urn:svcPaymentCash/GetPaymentCashDResponse")]
        System.IAsyncResult BeginGetPaymentCashD(string random, long payment_cash_id, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD> EndGetPaymentCashD(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:svcPaymentCash/GetPaymentCashList", ReplyAction="urn:svcPaymentCash/GetPaymentCashListResponse")]
        System.IAsyncResult BeginGetPaymentCashList(string random, string strWhereSql, string strOrderBySql, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCash> EndGetPaymentCashList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:svcPaymentCash/UpdatePaymentCash", ReplyAction="urn:svcPaymentCash/UpdatePaymentCashResponse")]
        System.IAsyncResult BeginUpdatePaymentCash(string random, int type, long PaymentCashNo, SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD> entityD, SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH before_entityH, System.AsyncCallback callback, object asyncState);
        
        string EndUpdatePaymentCash(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface svcPaymentCashChannel : SlvHanbaiClient.svcPaymentCash.svcPaymentCash, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPaymentCashHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPaymentCashHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPaymentCashDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPaymentCashDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPaymentCashListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPaymentCashListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCash> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCash>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdatePaymentCashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdatePaymentCashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class svcPaymentCashClient : System.ServiceModel.ClientBase<SlvHanbaiClient.svcPaymentCash.svcPaymentCash>, SlvHanbaiClient.svcPaymentCash.svcPaymentCash {
        
        private BeginOperationDelegate onBeginGetPaymentCashHDelegate;
        
        private EndOperationDelegate onEndGetPaymentCashHDelegate;
        
        private System.Threading.SendOrPostCallback onGetPaymentCashHCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPaymentCashDDelegate;
        
        private EndOperationDelegate onEndGetPaymentCashDDelegate;
        
        private System.Threading.SendOrPostCallback onGetPaymentCashDCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPaymentCashListDelegate;
        
        private EndOperationDelegate onEndGetPaymentCashListDelegate;
        
        private System.Threading.SendOrPostCallback onGetPaymentCashListCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdatePaymentCashDelegate;
        
        private EndOperationDelegate onEndUpdatePaymentCashDelegate;
        
        private System.Threading.SendOrPostCallback onUpdatePaymentCashCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public svcPaymentCashClient() {
        }
        
        public svcPaymentCashClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public svcPaymentCashClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcPaymentCashClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcPaymentCashClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("CookieContainer を設定できません。バインドに HttpCookieContainerBindingElement が含まれていることを確認してくだ" +
                            "さい。");
                }
            }
        }
        
        public event System.EventHandler<GetPaymentCashHCompletedEventArgs> GetPaymentCashHCompleted;
        
        public event System.EventHandler<GetPaymentCashDCompletedEventArgs> GetPaymentCashDCompleted;
        
        public event System.EventHandler<GetPaymentCashListCompletedEventArgs> GetPaymentCashListCompleted;
        
        public event System.EventHandler<UpdatePaymentCashCompletedEventArgs> UpdatePaymentCashCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SlvHanbaiClient.svcPaymentCash.svcPaymentCash.BeginGetPaymentCashH(string random, long payment_cash_no, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPaymentCashH(random, payment_cash_no, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH SlvHanbaiClient.svcPaymentCash.svcPaymentCash.EndGetPaymentCashH(System.IAsyncResult result) {
            return base.Channel.EndGetPaymentCashH(result);
        }
        
        private System.IAsyncResult OnBeginGetPaymentCashH(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string random = ((string)(inValues[0]));
            long payment_cash_no = ((long)(inValues[1]));
            return ((SlvHanbaiClient.svcPaymentCash.svcPaymentCash)(this)).BeginGetPaymentCashH(random, payment_cash_no, callback, asyncState);
        }
        
        private object[] OnEndGetPaymentCashH(System.IAsyncResult result) {
            SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH retVal = ((SlvHanbaiClient.svcPaymentCash.svcPaymentCash)(this)).EndGetPaymentCashH(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPaymentCashHCompleted(object state) {
            if ((this.GetPaymentCashHCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPaymentCashHCompleted(this, new GetPaymentCashHCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPaymentCashHAsync(string random, long payment_cash_no) {
            this.GetPaymentCashHAsync(random, payment_cash_no, null);
        }
        
        public void GetPaymentCashHAsync(string random, long payment_cash_no, object userState) {
            if ((this.onBeginGetPaymentCashHDelegate == null)) {
                this.onBeginGetPaymentCashHDelegate = new BeginOperationDelegate(this.OnBeginGetPaymentCashH);
            }
            if ((this.onEndGetPaymentCashHDelegate == null)) {
                this.onEndGetPaymentCashHDelegate = new EndOperationDelegate(this.OnEndGetPaymentCashH);
            }
            if ((this.onGetPaymentCashHCompletedDelegate == null)) {
                this.onGetPaymentCashHCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPaymentCashHCompleted);
            }
            base.InvokeAsync(this.onBeginGetPaymentCashHDelegate, new object[] {
                        random,
                        payment_cash_no}, this.onEndGetPaymentCashHDelegate, this.onGetPaymentCashHCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SlvHanbaiClient.svcPaymentCash.svcPaymentCash.BeginGetPaymentCashD(string random, long payment_cash_id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPaymentCashD(random, payment_cash_id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD> SlvHanbaiClient.svcPaymentCash.svcPaymentCash.EndGetPaymentCashD(System.IAsyncResult result) {
            return base.Channel.EndGetPaymentCashD(result);
        }
        
        private System.IAsyncResult OnBeginGetPaymentCashD(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string random = ((string)(inValues[0]));
            long payment_cash_id = ((long)(inValues[1]));
            return ((SlvHanbaiClient.svcPaymentCash.svcPaymentCash)(this)).BeginGetPaymentCashD(random, payment_cash_id, callback, asyncState);
        }
        
        private object[] OnEndGetPaymentCashD(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD> retVal = ((SlvHanbaiClient.svcPaymentCash.svcPaymentCash)(this)).EndGetPaymentCashD(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPaymentCashDCompleted(object state) {
            if ((this.GetPaymentCashDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPaymentCashDCompleted(this, new GetPaymentCashDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPaymentCashDAsync(string random, long payment_cash_id) {
            this.GetPaymentCashDAsync(random, payment_cash_id, null);
        }
        
        public void GetPaymentCashDAsync(string random, long payment_cash_id, object userState) {
            if ((this.onBeginGetPaymentCashDDelegate == null)) {
                this.onBeginGetPaymentCashDDelegate = new BeginOperationDelegate(this.OnBeginGetPaymentCashD);
            }
            if ((this.onEndGetPaymentCashDDelegate == null)) {
                this.onEndGetPaymentCashDDelegate = new EndOperationDelegate(this.OnEndGetPaymentCashD);
            }
            if ((this.onGetPaymentCashDCompletedDelegate == null)) {
                this.onGetPaymentCashDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPaymentCashDCompleted);
            }
            base.InvokeAsync(this.onBeginGetPaymentCashDDelegate, new object[] {
                        random,
                        payment_cash_id}, this.onEndGetPaymentCashDDelegate, this.onGetPaymentCashDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SlvHanbaiClient.svcPaymentCash.svcPaymentCash.BeginGetPaymentCashList(string random, string strWhereSql, string strOrderBySql, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPaymentCashList(random, strWhereSql, strOrderBySql, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCash> SlvHanbaiClient.svcPaymentCash.svcPaymentCash.EndGetPaymentCashList(System.IAsyncResult result) {
            return base.Channel.EndGetPaymentCashList(result);
        }
        
        private System.IAsyncResult OnBeginGetPaymentCashList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string random = ((string)(inValues[0]));
            string strWhereSql = ((string)(inValues[1]));
            string strOrderBySql = ((string)(inValues[2]));
            return ((SlvHanbaiClient.svcPaymentCash.svcPaymentCash)(this)).BeginGetPaymentCashList(random, strWhereSql, strOrderBySql, callback, asyncState);
        }
        
        private object[] OnEndGetPaymentCashList(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCash> retVal = ((SlvHanbaiClient.svcPaymentCash.svcPaymentCash)(this)).EndGetPaymentCashList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPaymentCashListCompleted(object state) {
            if ((this.GetPaymentCashListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPaymentCashListCompleted(this, new GetPaymentCashListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPaymentCashListAsync(string random, string strWhereSql, string strOrderBySql) {
            this.GetPaymentCashListAsync(random, strWhereSql, strOrderBySql, null);
        }
        
        public void GetPaymentCashListAsync(string random, string strWhereSql, string strOrderBySql, object userState) {
            if ((this.onBeginGetPaymentCashListDelegate == null)) {
                this.onBeginGetPaymentCashListDelegate = new BeginOperationDelegate(this.OnBeginGetPaymentCashList);
            }
            if ((this.onEndGetPaymentCashListDelegate == null)) {
                this.onEndGetPaymentCashListDelegate = new EndOperationDelegate(this.OnEndGetPaymentCashList);
            }
            if ((this.onGetPaymentCashListCompletedDelegate == null)) {
                this.onGetPaymentCashListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPaymentCashListCompleted);
            }
            base.InvokeAsync(this.onBeginGetPaymentCashListDelegate, new object[] {
                        random,
                        strWhereSql,
                        strOrderBySql}, this.onEndGetPaymentCashListDelegate, this.onGetPaymentCashListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SlvHanbaiClient.svcPaymentCash.svcPaymentCash.BeginUpdatePaymentCash(string random, int type, long PaymentCashNo, SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD> entityD, SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH before_entityH, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdatePaymentCash(random, type, PaymentCashNo, entityH, entityD, before_entityH, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string SlvHanbaiClient.svcPaymentCash.svcPaymentCash.EndUpdatePaymentCash(System.IAsyncResult result) {
            return base.Channel.EndUpdatePaymentCash(result);
        }
        
        private System.IAsyncResult OnBeginUpdatePaymentCash(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string random = ((string)(inValues[0]));
            int type = ((int)(inValues[1]));
            long PaymentCashNo = ((long)(inValues[2]));
            SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH entityH = ((SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH)(inValues[3]));
            System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD> entityD = ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD>)(inValues[4]));
            SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH before_entityH = ((SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH)(inValues[5]));
            return ((SlvHanbaiClient.svcPaymentCash.svcPaymentCash)(this)).BeginUpdatePaymentCash(random, type, PaymentCashNo, entityH, entityD, before_entityH, callback, asyncState);
        }
        
        private object[] OnEndUpdatePaymentCash(System.IAsyncResult result) {
            string retVal = ((SlvHanbaiClient.svcPaymentCash.svcPaymentCash)(this)).EndUpdatePaymentCash(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdatePaymentCashCompleted(object state) {
            if ((this.UpdatePaymentCashCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdatePaymentCashCompleted(this, new UpdatePaymentCashCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdatePaymentCashAsync(string random, int type, long PaymentCashNo, SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD> entityD, SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH before_entityH) {
            this.UpdatePaymentCashAsync(random, type, PaymentCashNo, entityH, entityD, before_entityH, null);
        }
        
        public void UpdatePaymentCashAsync(string random, int type, long PaymentCashNo, SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD> entityD, SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH before_entityH, object userState) {
            if ((this.onBeginUpdatePaymentCashDelegate == null)) {
                this.onBeginUpdatePaymentCashDelegate = new BeginOperationDelegate(this.OnBeginUpdatePaymentCash);
            }
            if ((this.onEndUpdatePaymentCashDelegate == null)) {
                this.onEndUpdatePaymentCashDelegate = new EndOperationDelegate(this.OnEndUpdatePaymentCash);
            }
            if ((this.onUpdatePaymentCashCompletedDelegate == null)) {
                this.onUpdatePaymentCashCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdatePaymentCashCompleted);
            }
            base.InvokeAsync(this.onBeginUpdatePaymentCashDelegate, new object[] {
                        random,
                        type,
                        PaymentCashNo,
                        entityH,
                        entityD,
                        before_entityH}, this.onEndUpdatePaymentCashDelegate, this.onUpdatePaymentCashCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SlvHanbaiClient.svcPaymentCash.svcPaymentCash CreateChannel() {
            return new svcPaymentCashClientChannel(this);
        }
        
        private class svcPaymentCashClientChannel : ChannelBase<SlvHanbaiClient.svcPaymentCash.svcPaymentCash>, SlvHanbaiClient.svcPaymentCash.svcPaymentCash {
            
            public svcPaymentCashClientChannel(System.ServiceModel.ClientBase<SlvHanbaiClient.svcPaymentCash.svcPaymentCash> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetPaymentCashH(string random, long payment_cash_no, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = random;
                _args[1] = payment_cash_no;
                System.IAsyncResult _result = base.BeginInvoke("GetPaymentCashH", _args, callback, asyncState);
                return _result;
            }
            
            public SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH EndGetPaymentCashH(System.IAsyncResult result) {
                object[] _args = new object[0];
                SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH _result = ((SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH)(base.EndInvoke("GetPaymentCashH", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPaymentCashD(string random, long payment_cash_id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = random;
                _args[1] = payment_cash_id;
                System.IAsyncResult _result = base.BeginInvoke("GetPaymentCashD", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD> EndGetPaymentCashD(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD> _result = ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD>)(base.EndInvoke("GetPaymentCashD", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPaymentCashList(string random, string strWhereSql, string strOrderBySql, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = random;
                _args[1] = strWhereSql;
                _args[2] = strOrderBySql;
                System.IAsyncResult _result = base.BeginInvoke("GetPaymentCashList", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCash> EndGetPaymentCashList(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCash> _result = ((System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCash>)(base.EndInvoke("GetPaymentCashList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdatePaymentCash(string random, int type, long PaymentCashNo, SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH entityH, System.Collections.ObjectModel.ObservableCollection<SlvHanbaiClient.svcPaymentCash.EntityPaymentCashD> entityD, SlvHanbaiClient.svcPaymentCash.EntityPaymentCashH before_entityH, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = random;
                _args[1] = type;
                _args[2] = PaymentCashNo;
                _args[3] = entityH;
                _args[4] = entityD;
                _args[5] = before_entityH;
                System.IAsyncResult _result = base.BeginInvoke("UpdatePaymentCash", _args, callback, asyncState);
                return _result;
            }
            
            public string EndUpdatePaymentCash(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("UpdatePaymentCash", _args, result)));
                return _result;
            }
        }
    }
}
